//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CFG_LOAIPHIEUTHU
    {
        public int ID_CFG_LOAIPHIEUTHU { get; set; }
        public Nullable<int> ID_LOAIPHIEUTHU { get; set; }
        public string ID_TAG { get; set; }
        public string VALUE { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
    }
}
