//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CONGTY
    {
        public int ID_CONGTY { get; set; }
        public string TENCONGTY { get; set; }
        public string DIACHICONGTY { get; set; }
        public string DTCONGTY { get; set; }
        public string FAXCONGTY { get; set; }
        public Nullable<int> ID_QUOCGIA { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public string DIENTHOAICONGTY { get; set; }
        public string EMAILCONGTY { get; set; }
    }
}
