//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHINHANH
    {
        public int ID_CHINHANH { get; set; }
        public string TENCHINHANH { get; set; }
        public string DIACHICHINHANH { get; set; }
        public string GHICHU { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public string DIENTHOAICHINHANH { get; set; }
        public string TENCHINHANHFULL { get; set; }
        public string EMAILCHINHANH { get; set; }
        public string FAXCHINHANH { get; set; }
        public string ID_CONGTY { get; set; }
    }
}
