//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DTTC
    {
        public int ID_DTTC { get; set; }
        public string TENDTTC { get; set; }
        public string MADTTC { get; set; }
        public string DIACHI { get; set; }
        public string DIDONG { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> JD_CHUCVU { get; set; }
        public Nullable<int> JD_PHONGBAN { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public Nullable<bool> ENABLE_DTTC { get; set; }
        public Nullable<int> ID_CHINHANH { get; set; }
        public string MATRUNGTAM { get; set; }
        public string MANHANVIEN { get; set; }
        public string MANGUOIQUANLY { get; set; }
        public string MAGIAMDOCTRUNGTAM { get; set; }
        public string MAGIAMDOCVUNG { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public Nullable<int> JD_BOPHAN { get; set; }
        public string GHICHU { get; set; }
        public string CHUCVU { get; set; }
        public string crm_vung { get; set; }
        public string qEC { get; set; }
        public string qLD { get; set; }
        public string qTT { get; set; }
        public string qV { get; set; }
    }
}
