//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GIAOVIEN
    {
        public int ID_GIAOVIEN { get; set; }
        public string MAGIAOVIEN { get; set; }
        public string TENGIAOVIEN { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public string QUOCTICH { get; set; }
        public string MA_LMS { get; set; }
    }
}
