//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HELP
    {
        public int ID_HELP { get; set; }
        public string CAUHOI { get; set; }
        public string NOIDUNG { get; set; }
        public string TENNGUOIHOI { get; set; }
        public int ID_DANHMUCCHINH { get; set; }
        public int ID_DANHMUCPHU { get; set; }
        public byte[] FILESNOIDUNG { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> ID_DTTC_TRALOI { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public byte[] FILECAUHOI { get; set; }
        public string TENNGUOITRALOI { get; set; }
        public byte[] FILENOTE1 { get; set; }
        public string NOIDUNGNOTE1 { get; set; }
        public string TENNGUOINOTE1 { get; set; }
        public Nullable<System.DateTime> NGAYNOTE1 { get; set; }
        public byte[] FILENOTE2 { get; set; }
        public string NOIDUNGNOTE2 { get; set; }
        public string TENNGUOINOTE2 { get; set; }
        public Nullable<System.DateTime> NGAYNOTE2 { get; set; }
        public byte[] FILENOTE3 { get; set; }
        public string NOIDUNGNOTE3 { get; set; }
        public string TENNGUOINOTE3 { get; set; }
        public Nullable<System.DateTime> NGAYNOTE3 { get; set; }
        public byte[] FILENOTE4 { get; set; }
        public string NOIDUNGNOTE4 { get; set; }
        public string TENNGUOINOTE4 { get; set; }
        public Nullable<System.DateTime> NGAYNOTE4 { get; set; }
        public byte[] FILENOTE5 { get; set; }
        public string NOIDUNGNOTE5 { get; set; }
        public string TENNGUOINOTE5 { get; set; }
        public Nullable<System.DateTime> NGAYNOTE5 { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
    }
}
