//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KT_AUTO_ButToanXuat
    {
        public int ID_BTTD { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> JD_LOAIPHIEUXUAT { get; set; }
        public Nullable<int> JD_DINHKHOAN_NO { get; set; }
        public Nullable<int> JD_DINHKHOAN_CO { get; set; }
        public string COTGIATRI { get; set; }
        public Nullable<bool> CUOIPHIEU { get; set; }
        public Nullable<bool> LAYSOLUONG { get; set; }
        public string DIEUKIEN { get; set; }
        public Nullable<bool> KICHHOAT { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
    }
}
