//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHOHANG
    {
        public int ID_KHOHANG { get; set; }
        public string TENKHOHANG { get; set; }
        public string TAIKHOAN { get; set; }
        public string TENTAIKHOAN { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public string MAKHO { get; set; }
    }
}
