//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAIKHACHHANG
    {
        public int ID_LOAIKHACHHANG { get; set; }
        public string TENLOAIKHACHHANG { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public Nullable<int> ID_TRUNGTAM { get; set; }
    }
}
