//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LINHVUC
    {
        public int ID_LINHVUC { get; set; }
        public string TENLINHVUC { get; set; }
        public Nullable<int> JD_NHOMLINHVUC { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
