//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAIEMAIL
    {
        public string TENLOAIEMAIL { get; set; }
        public int ID_LOAIEMAIL { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public string TIEUDEEMAIL { get; set; }
        public string NOIDUNGEMAIL { get; set; }
    }
}
