//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NOIDANGKY_BHXH
    {
        public int ID_NOIDANGKY { get; set; }
        public string MA_NOIDANGKY { get; set; }
        public string TEN_NOIDANGKY { get; set; }
        public string DIACHI { get; set; }
        public string GHICHU { get; set; }
        public string QUYENDULIEU { get; set; }
        public string QUANHUYEN { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
    }
}
