//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PHANNHOM1
    {
        public int ID_PHANNHOM1 { get; set; }
        public string TENPHANNHOM1 { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public Nullable<int> ID_LOAIHOSOKH { get; set; }
        public string HANGDN { get; set; }
        public string LOAIHINHDNN { get; set; }
        public Nullable<decimal> TONGSOVON { get; set; }
        public Nullable<decimal> GIATRIGOP { get; set; }
        public Nullable<decimal> TILEGOP { get; set; }
        public Nullable<decimal> SONGUOIDUOCCU { get; set; }
        public Nullable<decimal> TONGSONGUOI { get; set; }
    }
}
