//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TRUNGTAM
    {
        public int ID_TRUNGTAM { get; set; }
        public string TENTRUNGTAM { get; set; }
        public string DIACHITRUNGTAM { get; set; }
        public string DIENTHOAITRUNGTAM { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public string MA_DVCS { get; set; }
        public string MA_EFFECT { get; set; }
        public string MA_LMS { get; set; }
        public string MA_VUNG { get; set; }
        public string ma_crm { get; set; }
        public Nullable<int> ID_KHUVUC { get; set; }
        public string MA_GIAMDOCTT { get; set; }
    }
}
