//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TIEMNANG
    {
        public int ID_TIEMNANG { get; set; }
        public string TENTIEMNANG { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public string PREFIX { get; set; }
    }
}
