//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_VUNG
    {
        public int ID_VUNG { get; set; }
        public string MAVUNG { get; set; }
        public string TENVUNG { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public string MA_GIAMDOCVUNG { get; set; }
        public string ma_crm { get; set; }
    }
}
