//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_AUTO_REPORT_KH
    {
        public int ID_AUTO_REPORT_KH { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public int J_AUTO_REPORT { get; set; }
    }
}
