//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_AUTO_REPORTS
    {
        public int ID_AUTO_REPORTS { get; set; }
        public string FILENAME_REPORTS { get; set; }
        public Nullable<int> ID_LOAIBAOCAO { get; set; }
        public Nullable<bool> NHANTINNHAN { get; set; }
        public Nullable<int> THOIGIANBAOCAO { get; set; }
        public Nullable<int> THUCHIEN { get; set; }
        public Nullable<int> THUCHIENCON { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<bool> CHECKNGAY { get; set; }
        public Nullable<bool> CHECKTUAN { get; set; }
        public Nullable<bool> CHECKTHANG { get; set; }
        public bool DATHUCHIEN { get; set; }
        public int ID_DTTC { get; set; }
        public byte[] FILE_LAYOUT { get; set; }
        public Nullable<bool> EMAILTHONGKE { get; set; }
        public int TAIKHOANGUI { get; set; }
        public Nullable<int> TIME_SEND { get; set; }
    }
}
