//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_BAOCAO
    {
        public int A_BAOCAO { get; set; }
        public string BAOCAO { get; set; }
        public string TENBAOCAO { get; set; }
        public string NHOMBAOCAO { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public string NGUOIDUNG { get; set; }
        public string NGUOIDUNGNHOM { get; set; }
        public string GHICHU { get; set; }
    }
}
