//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CACMAUBAOCAO
    {
        public int A_BAOCAO { get; set; }
        public int ID_LOAIBAOCAO { get; set; }
        public int ID_LOAIBAOCAOCON { get; set; }
        public string TENBAOCAO { get; set; }
        public string TENFILE { get; set; }
        public Nullable<bool> DEFAUL { get; set; }
        public byte[] FILEDINHDANG { get; set; }
        public string KEYS { get; set; }
    }
}
