//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CONGCU_TIMKIEM
    {
        public int A_CONGCU_TIMKIEM { get; set; }
        public string BAOCAO { get; set; }
        public string FORMNAME { get; set; }
        public string LABELTEXT { get; set; }
        public Nullable<int> LABELWIDTH { get; set; }
        public string FIELD { get; set; }
        public Nullable<bool> VISIBLE { get; set; }
        public string FROMTABLE { get; set; }
        public string VALUETYPE { get; set; }
        public string DEFAULTVALUE { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
