//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CONFIG_VAL_BY_DM
    {
        public int A_CONFIG_VAL_BY_DM { get; set; }
        public int ID_DTTC { get; set; }
        public string DM_TAG { get; set; }
        public int ID_DM { get; set; }
        public string Type { get; set; }
        public string VAL { get; set; }
    }
}
