//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CFG_FUNC
    {
        public int A_CFG_FUNC { get; set; }
        public string FORM { get; set; }
        public string CONTROL_NAME { get; set; }
        public string CONTROL_TEXT { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string MAY1 { get; set; }
        public string NGUOI1 { get; set; }
    }
}
