//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CHART_LAYOUT
    {
        public int ID_LAYOUT_CHART { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> GD { get; set; }
        public Nullable<int> NT { get; set; }
        public Nullable<int> EM { get; set; }
        public Nullable<int> SMS { get; set; }
        public Nullable<int> HL { get; set; }
        public Nullable<int> BG { get; set; }
        public Nullable<int> DB { get; set; }
        public Nullable<int> HD { get; set; }
        public Nullable<int> XH { get; set; }
        public Nullable<int> TT { get; set; }
        public Nullable<int> NH { get; set; }
        public Nullable<int> CT { get; set; }
    }
}
