//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CHART_PNL
    {
        public int ID_CHART_PNL { get; set; }
        public string PNL_NAME { get; set; }
        public Nullable<int> iWITH { get; set; }
        public Nullable<int> iHEIGHT { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public string TEXT_NAME { get; set; }
        public string TAG { get; set; }
    }
}
