//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CONFIG_MCC_THIETLAPCA
    {
        public int ID_CA { get; set; }
        public string MACA { get; set; }
        public Nullable<System.DateTime> GIOVAO { get; set; }
        public Nullable<System.DateTime> GIORA { get; set; }
        public Nullable<System.DateTime> BATDAUVAO { get; set; }
        public Nullable<System.DateTime> KETTHUCVAO { get; set; }
        public Nullable<System.DateTime> BATDAURA { get; set; }
        public Nullable<System.DateTime> KETTHUCRA { get; set; }
        public Nullable<System.DateTime> BATDAUANTRUA { get; set; }
        public Nullable<System.DateTime> KETTHUCANTRUA { get; set; }
        public Nullable<bool> CADEM { get; set; }
        public Nullable<int> ID_NHOMLINHVUC { get; set; }
    }
}
