//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CHART
    {
        public int ID_CHART { get; set; }
        public string CHARTNAME { get; set; }
        public Nullable<int> ISPHANTICH { get; set; }
        public int ID_LOAITHUCHIEN { get; set; }
        public int ID_THUCHIENCON { get; set; }
        public Nullable<int> TYPECHART { get; set; }
        public string COTTEXT { get; set; }
        public string COTSO { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public string ID_DTTCS { get; set; }
        public Nullable<bool> DEFAULTS { get; set; }
        public string TENFILEDINHDANG { get; set; }
        public string COLUMNFILTERNO { get; set; }
        public string KEYS { get; set; }
    }
}
