//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_GRIDEX_VISIBEL
    {
        public int ID_COLUMN { get; set; }
        public string FILENAME { get; set; }
        public string COLUMNNAME { get; set; }
        public bool VISIBEL { get; set; }
        public int TABLES { get; set; }
    }
}
