//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_HETHONG
    {
        public int HETHONG { get; set; }
        public string MACOQUAN { get; set; }
        public string COQUANCHUQUAN { get; set; }
        public string TENCOQUAN { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string FAX { get; set; }
        public string MAIL { get; set; }
        public string WEBSITE { get; set; }
        public byte[] LOGO { get; set; }
        public byte[] NENCHO { get; set; }
        public string PATHSERVER { get; set; }
        public string SOLUONG { get; set; }
        public string MAPHANMEM { get; set; }
        public string MATKHAU { get; set; }
        public string MAGT { get; set; }
        public string TENGIOITHIEU { get; set; }
        public string DTIENTHOAIGT { get; set; }
        public string EMAILGT { get; set; }
        public string NGAYDANGKY { get; set; }
        public string TIENTOKH { get; set; }
        public string TIENTOSP { get; set; }
        public string TIENTOBG { get; set; }
        public string TIENTODH { get; set; }
        public string TIENTOHD { get; set; }
        public string TIENTOXH { get; set; }
        public string TIENTOTT { get; set; }
        public string TIENTONH { get; set; }
        public string TIENTOCT { get; set; }
        public Nullable<bool> SINHNHAT { get; set; }
        public Nullable<int> TRUOCNGAY { get; set; }
        public Nullable<bool> PUBLICS { get; set; }
        public Nullable<int> NUMBEREMAIL { get; set; }
        public Nullable<int> NUMBERTIME { get; set; }
        public Nullable<bool> DANGDUNGEMAIL { get; set; }
        public string THONGDIEPVPAR_KHACHHANG { get; set; }
        public Nullable<bool> EDITABLESP { get; set; }
        public string THOIGIANKHOASO { get; set; }
        public string DATELOCK { get; set; }
        public string MAKH { get; set; }
    }
}
