//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_KHAIBAO_KHACHHANG_REG
    {
        public int ID { get; set; }
        public string NAMECOMPUTER { get; set; }
        public string WORKGROUP { get; set; }
        public Nullable<System.DateTime> DATEDEC { get; set; }
        public Nullable<bool> LOCK { get; set; }
        public string USERNAME { get; set; }
        public string MADANGKY { get; set; }
        public Nullable<decimal> COUNTCT { get; set; }
        public Nullable<decimal> COUNTMAU { get; set; }
        public string UID { get; set; }
        public Nullable<int> A_HOSOKHACHHANG { get; set; }
        public string TENKHACHHANG { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string TENNGUOIDANGKY { get; set; }
        public string DIDONG { get; set; }
        public string EMAILNGUOIDANGKY { get; set; }
        public string MAGIOITHIEU { get; set; }
        public string TENNGUOIGIOITHIEU { get; set; }
        public string DIDONGNGUOIGIOITHIEU { get; set; }
        public string EMAILNGUOIGIOITHIEU { get; set; }
        public string CPUID { get; set; }
        public string MACADRESS { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
    }
}
