//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_KHAIBAO
    {
        public int ID { get; set; }
        public string NAMECOMPUTER { get; set; }
        public string WORKGROUP { get; set; }
        public Nullable<System.DateTime> DATEDEC { get; set; }
        public Nullable<bool> LOCK { get; set; }
        public string USERNAME { get; set; }
        public string MADANGKY { get; set; }
        public Nullable<decimal> COUNTCT { get; set; }
        public Nullable<decimal> COUNTMAU { get; set; }
    }
}
