//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_LAYOUT_TAB
    {
        public int A_LAYOUT_TAB { get; set; }
        public string FELD_NAME { get; set; }
        public string CAPTION { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public Nullable<int> WIDTH_SHOW { get; set; }
        public Nullable<bool> VISIBEL { get; set; }
        public Nullable<int> ID_TAB { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
    }
}
