//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_MENU_EXP
    {
        public int A_MENU_EXP { get; set; }
        public string TENMENU { get; set; }
        public string KEYS { get; set; }
        public string TENMENU_EN { get; set; }
        public string TENMENU_JP { get; set; }
    }
}
