//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NUMBER_PHONE
    {
        public int ID_NUMBER_MOBILE { get; set; }
        public string NUMBER_PHONE { get; set; }
        public string PASSWORD { get; set; }
        public int ID_DTTC { get; set; }
    }
}
