//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NHOMNGUOIDUNG
    {
        public int NHOMNGUOIDUNG { get; set; }
        public string TENNHOMNGUOIDUNG { get; set; }
        public string QUYEN { get; set; }
        public Nullable<bool> ISDEL { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public Nullable<int> NGUOIDUNG2 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public Nullable<System.DateTime> NGAY2 { get; set; }
        public string MAY1 { get; set; }
        public string MAY2 { get; set; }
    }
}
