//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NGUOIDUYET
    {
        public int ID_HETHONGDUYET { get; set; }
        public Nullable<int> ID_LOAITHUCHIEN { get; set; }
        public string NGUOIDUYET { get; set; }
    }
}
