//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NGUOIDUNG
    {
        public int NGUOIDUNG { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public string GHICHU { get; set; }
        public string QUYEN { get; set; }
        public Nullable<short> NguoiDung1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public Nullable<short> NguoiDung2 { get; set; }
        public Nullable<System.DateTime> NGAY2 { get; set; }
        public Nullable<bool> Del { get; set; }
        public string MaKhuVuc { get; set; }
        public Nullable<int> NHOMNGUOIDUNG { get; set; }
        public string NGONNGU { get; set; }
        public string PLATFORM { get; set; }
        public string REGID { get; set; }
        public Nullable<int> TrungTam { get; set; }
    }
}
