//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NHOMBAOCAO
    {
        public int A_NHOMBAOCAO { get; set; }
        public string NHOMBAOCAO { get; set; }
        public string TENNHOMBAOCAO { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
    }
}
