//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_QUYENSUDUNG
    {
        public int QUYENSUDUNG { get; set; }
        public string TENQUYENSUDUNG { get; set; }
        public Nullable<int> NHOMQUYEN { get; set; }
        public string TABLELINK { get; set; }
        public bool ISDEL { get; set; }
    }
}
