//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_REPORTS
    {
        public int ID_REPORTS { get; set; }
        public string REPORTSNAME { get; set; }
        public string FILENAME { get; set; }
        public string KEYS { get; set; }
        public Nullable<int> ID_REPORTSTYPE { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public string NAME_REPORTSTYPE { get; set; }
        public string SQLHEADER { get; set; }
        public string CHILD1 { get; set; }
        public string SQLCHILD { get; set; }
    }
}
