//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_REPORTS_SIGN
    {
        public int ID_REPORT_SIGN { get; set; }
        public int J_REPORTS { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> TO_ORDER { get; set; }
    }
}
