//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_SQL
    {
        public int A_SQL { get; set; }
        public string KEYS { get; set; }
        public string SQL_COMM { get; set; }
        public string SQL_DESIGN { get; set; }
        public string SQL_CAPTION { get; set; }
        public string NHOM { get; set; }
        public string FORMNAME { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public Nullable<int> PHANTICH_TUDO { get; set; }
        public string QUYENNGUOIDUNG { get; set; }
        public Nullable<int> HENLICH { get; set; }
        public string REPORTS { get; set; }
        public string SQLHEADER { get; set; }
        public string CHILD1 { get; set; }
    }
}
