//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_THUMAU
    {
        public int ID_THUMAU { get; set; }
        public string TIEUDE { get; set; }
        public byte[] FILENOIDUNG { get; set; }
        public string PATHFILE { get; set; }
        public string HTMLCODE { get; set; }
        public string VARIABLE { get; set; }
    }
}
