//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_TABLES_COLUMN
    {
        public int A_HT_TABLES_COLUMN { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string VIETNAM { get; set; }
        public Nullable<int> ORDINAL_POSITION { get; set; }
        public string TABLE_REF { get; set; }
        public string TAB_VALUE { get; set; }
        public string TAB_DISPLAY { get; set; }
        public Nullable<int> WIDTH { get; set; }
    }
}
