//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_UPDATE_DATA
    {
        public int A_UPDATE_DATA { get; set; }
        public string ID_COMMAND_SQL { get; set; }
        public Nullable<int> ID_DATATYPE_FROM { get; set; }
        public string TABLE_FROM { get; set; }
        public string TABLE_TO { get; set; }
        public Nullable<int> ORDERS { get; set; }
        public string SCONNECT_FROM { get; set; }
        public string SQLEXQ { get; set; }
    }
}
