//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_UPDATE_DATA_DETAIL
    {
        public int A_UPDATE_DATA_DETAIL { get; set; }
        public int J_UPDATE_DATA { get; set; }
        public string COLUMN_FROM { get; set; }
        public string COLUMN_TO { get; set; }
        public string TABLE_RE { get; set; }
        public string COLUMN_RE { get; set; }
        public Nullable<bool> KEYS { get; set; }
        public string DATA_TYPE { get; set; }
    }
}
