//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_BCTC_CanDoiKeToan
    {
        public int ID { get; set; }
        public Nullable<int> STT { get; set; }
        public string VN_CHITIEU { get; set; }
        public string EN_CHITIEU { get; set; }
        public string JP_CHITIEU { get; set; }
        public string MASO { get; set; }
        public string TM { get; set; }
        public string KYTRUOC { get; set; }
        public string TRONGKY { get; set; }
    }
}
