//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APAXEntities3 : DbContext
    {
        public APAXEntities3()
            : base("name=APAXEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_CHUNHIEM_DA> DM_CHUNHIEM_DA { get; set; }
        public virtual DbSet<DM_CHUTRIBOMON> DM_CHUTRIBOMON { get; set; }
        public virtual DbSet<DM_CONGCU> DM_CONGCU { get; set; }
        public virtual DbSet<DM_GIAMDOCDUAN> DM_GIAMDOCDUAN { get; set; }
        public virtual DbSet<DM_GIOBOOK> DM_GIOBOOK { get; set; }
        public virtual DbSet<DM_LOAIKEHOACH> DM_LOAIKEHOACH { get; set; }
        public virtual DbSet<DM_LYDO_NT> DM_LYDO_NT { get; set; }
        public virtual DbSet<DM_LYDO_TD> DM_LYDO_TD { get; set; }
        public virtual DbSet<DM_PHANLOAINHANSU> DM_PHANLOAINHANSU { get; set; }
        public virtual DbSet<DM_PHUONGTHUC> DM_PHUONGTHUC { get; set; }
        public virtual DbSet<DM_QUOCGIA> DM_QUOCGIA { get; set; }
        public virtual DbSet<DM_TRUNGTAM> DM_TRUNGTAM { get; set; }
        public virtual DbSet<HT_CONFIG_HOLIDAY> HT_CONFIG_HOLIDAY { get; set; }
        public virtual DbSet<HT_NGUOIDUNG> HT_NGUOIDUNG { get; set; }
        public virtual DbSet<HT_NHOMNGUOIDUNG> HT_NHOMNGUOIDUNG { get; set; }
        public virtual DbSet<HT_NHOMQUYEN> HT_NHOMQUYEN { get; set; }
        public virtual DbSet<HT_QUYENSUDUNG> HT_QUYENSUDUNG { get; set; }
        public virtual DbSet<QL_LopHoc> QL_LopHoc { get; set; }
        public virtual DbSet<TH_BAOLUU> TH_BAOLUU { get; set; }
        public virtual DbSet<TH_DANGKYCHUYENLOP> TH_DANGKYCHUYENLOP { get; set; }
        public virtual DbSet<TH_DANGKYCHUYENPHI> TH_DANGKYCHUYENPHI { get; set; }
        public virtual DbSet<TH_DIEMDANH> TH_DIEMDANH { get; set; }
        public virtual DbSet<TH_DUBAO_FILE> TH_DUBAO_FILE { get; set; }
        public virtual DbSet<TH_DUBAO_SANPHAM> TH_DUBAO_SANPHAM { get; set; }
        public virtual DbSet<TH_DUYETTHUCHIEN> TH_DUYETTHUCHIEN { get; set; }
        public virtual DbSet<TH_HOPDONG_SP> TH_HOPDONG_SP { get; set; }
        public virtual DbSet<TH_HOSODTDTC> TH_HOSODTDTC { get; set; }
        public virtual DbSet<TH_KEHOACH> TH_KEHOACH { get; set; }
        public virtual DbSet<TH_KEHOACH_FILE> TH_KEHOACH_FILE { get; set; }
        public virtual DbSet<TH_KEHOACH_KHACHHANG> TH_KEHOACH_KHACHHANG { get; set; }
        public virtual DbSet<TH_WORKINGTIMEDAILY> TH_WORKINGTIMEDAILY { get; set; }
        public virtual DbSet<DM_BACLUONG> DM_BACLUONG { get; set; }
        public virtual DbSet<DM_BOPHAN> DM_BOPHAN { get; set; }
        public virtual DbSet<DM_CFG_LOAIPHIEUCHI> DM_CFG_LOAIPHIEUCHI { get; set; }
        public virtual DbSet<DM_CFG_LOAIPHIEUNHAP> DM_CFG_LOAIPHIEUNHAP { get; set; }
        public virtual DbSet<DM_CFG_LOAIPHIEUTHU> DM_CFG_LOAIPHIEUTHU { get; set; }
        public virtual DbSet<DM_CFG_LOAIPHIEUXUAT> DM_CFG_LOAIPHIEUXUAT { get; set; }
        public virtual DbSet<DM_CHINH> DM_CHINH { get; set; }
        public virtual DbSet<DM_CHINHANH> DM_CHINHANH { get; set; }
        public virtual DbSet<DM_CHUCVU> DM_CHUCVU { get; set; }
        public virtual DbSet<DM_CONGTHUCTINHTOAN> DM_CONGTHUCTINHTOAN { get; set; }
        public virtual DbSet<DM_CONGTY> DM_CONGTY { get; set; }
        public virtual DbSet<DM_DATHANG> DM_DATHANG { get; set; }
        public virtual DbSet<DM_DINHKHOAN> DM_DINHKHOAN { get; set; }
        public virtual DbSet<DM_DONVITINH> DM_DONVITINH { get; set; }
        public virtual DbSet<DM_DUYET> DM_DUYET { get; set; }
        public virtual DbSet<DM_GIAOVIEN> DM_GIAOVIEN { get; set; }
        public virtual DbSet<DM_GIOITINH> DM_GIOITINH { get; set; }
        public virtual DbSet<DM_HANGSANXUAT> DM_HANGSANXUAT { get; set; }
        public virtual DbSet<DM_HANGVANCHUYEN> DM_HANGVANCHUYEN { get; set; }
        public virtual DbSet<DM_HANHVI> DM_HANHVI { get; set; }
        public virtual DbSet<DM_HELP> DM_HELP { get; set; }
        public virtual DbSet<DM_HELP_NOTE> DM_HELP_NOTE { get; set; }
        public virtual DbSet<DM_KENHBANHANG> DM_KENHBANHANG { get; set; }
        public virtual DbSet<DM_KHANCAP> DM_KHANCAP { get; set; }
        public virtual DbSet<DM_KHOHANG> DM_KHOHANG { get; set; }
        public virtual DbSet<DM_KT_AUTO_ButToanNhap> DM_KT_AUTO_ButToanNhap { get; set; }
        public virtual DbSet<DM_KT_AUTO_ButToanXuat> DM_KT_AUTO_ButToanXuat { get; set; }
        public virtual DbSet<DM_LINHVUC> DM_LINHVUC { get; set; }
        public virtual DbSet<DM_LOAIBAOCAO> DM_LOAIBAOCAO { get; set; }
        public virtual DbSet<DM_LOAIBAOGIA> DM_LOAIBAOGIA { get; set; }
        public virtual DbSet<DM_LOAIDATHANG> DM_LOAIDATHANG { get; set; }
        public virtual DbSet<DM_LOAIDTDTC> DM_LOAIDTDTC { get; set; }
        public virtual DbSet<DM_LOAIEMAIL> DM_LOAIEMAIL { get; set; }
        public virtual DbSet<DM_LOAIHEN> DM_LOAIHEN { get; set; }
        public virtual DbSet<DM_LOAIHINH> DM_LOAIHINH { get; set; }
        public virtual DbSet<DM_LOAIHINHNGHI> DM_LOAIHINHNGHI { get; set; }
        public virtual DbSet<DM_LOAIHOSOKH> DM_LOAIHOSOKH { get; set; }
        public virtual DbSet<DM_LOAIKHACHHANG> DM_LOAIKHACHHANG { get; set; }
        public virtual DbSet<DM_LOAIPHIEUCHI> DM_LOAIPHIEUCHI { get; set; }
        public virtual DbSet<DM_LOAIPHIEUNHAP> DM_LOAIPHIEUNHAP { get; set; }
        public virtual DbSet<DM_LOAIPHIEUTHU> DM_LOAIPHIEUTHU { get; set; }
        public virtual DbSet<DM_LOAIPHIEUXUAT> DM_LOAIPHIEUXUAT { get; set; }
        public virtual DbSet<DM_LOAISANPHAM> DM_LOAISANPHAM { get; set; }
        public virtual DbSet<DM_LOAISMS> DM_LOAISMS { get; set; }
        public virtual DbSet<DM_LOAITHU> DM_LOAITHU { get; set; }
        public virtual DbSet<DM_LOAITIEN> DM_LOAITIEN { get; set; }
        public virtual DbSet<DM_LOAIVPAR> DM_LOAIVPAR { get; set; }
        public virtual DbSet<DM_LYDOHV> DM_LYDOHV { get; set; }
        public virtual DbSet<DM_LYDONT> DM_LYDONT { get; set; }
        public virtual DbSet<DM_LYDOTD> DM_LYDOTD { get; set; }
        public virtual DbSet<DM_MUCDICH> DM_MUCDICH { get; set; }
        public virtual DbSet<DM_MUCDICHHD> DM_MUCDICHHD { get; set; }
        public virtual DbSet<DM_MUCSANPHAM> DM_MUCSANPHAM { get; set; }
        public virtual DbSet<DM_NGANHANG> DM_NGANHANG { get; set; }
        public virtual DbSet<DM_NGAY> DM_NGAY { get; set; }
        public virtual DbSet<DM_NGAYNGHIPHEPNAM> DM_NGAYNGHIPHEPNAM { get; set; }
        public virtual DbSet<DM_NGUONPHANHOI> DM_NGUONPHANHOI { get; set; }
        public virtual DbSet<DM_NHANTHUC> DM_NHANTHUC { get; set; }
        public virtual DbSet<DM_NHAPHANPHOI> DM_NHAPHANPHOI { get; set; }
        public virtual DbSet<DM_NHIEMVUCHUAN> DM_NHIEMVUCHUAN { get; set; }
        public virtual DbSet<DM_NHOMLINHVUC> DM_NHOMLINHVUC { get; set; }
        public virtual DbSet<DM_NHOMLUONG> DM_NHOMLUONG { get; set; }
        public virtual DbSet<DM_NHOMSANPHAM> DM_NHOMSANPHAM { get; set; }
        public virtual DbSet<DM_NOIDANGKY_BHXH> DM_NOIDANGKY_BHXH { get; set; }
        public virtual DbSet<DM_NUOCSANXUAT> DM_NUOCSANXUAT { get; set; }
        public virtual DbSet<DM_PHANLOAI1> DM_PHANLOAI1 { get; set; }
        public virtual DbSet<DM_PHANLOAI2> DM_PHANLOAI2 { get; set; }
        public virtual DbSet<DM_PHANLOAI3> DM_PHANLOAI3 { get; set; }
        public virtual DbSet<DM_PHANLOAI4> DM_PHANLOAI4 { get; set; }
        public virtual DbSet<DM_PHANLOAINX1> DM_PHANLOAINX1 { get; set; }
        public virtual DbSet<DM_PHANLOAIUNGVIEN> DM_PHANLOAIUNGVIEN { get; set; }
        public virtual DbSet<DM_PHANLOAIXN2> DM_PHANLOAIXN2 { get; set; }
        public virtual DbSet<DM_PHANNHOM1> DM_PHANNHOM1 { get; set; }
        public virtual DbSet<DM_PHANNHOM2> DM_PHANNHOM2 { get; set; }
        public virtual DbSet<DM_PHANXUONG> DM_PHANXUONG { get; set; }
        public virtual DbSet<DM_PHONGBAN> DM_PHONGBAN { get; set; }
        public virtual DbSet<DM_PHONGHOP> DM_PHONGHOP { get; set; }
        public virtual DbSet<DM_PHU> DM_PHU { get; set; }
        public virtual DbSet<DM_PHUONGPHAPTINH> DM_PHUONGPHAPTINH { get; set; }
        public virtual DbSet<DM_QUANHUYEN> DM_QUANHUYEN { get; set; }
        public virtual DbSet<DM_QUOCTICH> DM_QUOCTICH { get; set; }
        public virtual DbSet<DM_QUYEN> DM_QUYEN { get; set; }
        public virtual DbSet<DM_TEXT> DM_TEXT { get; set; }
        public virtual DbSet<DM_THAIDO> DM_THAIDO { get; set; }
        public virtual DbSet<DM_THANG> DM_THANG { get; set; }
        public virtual DbSet<DM_THOIGIAN_PT> DM_THOIGIAN_PT { get; set; }
        public virtual DbSet<DM_THOIGIANBH> DM_THOIGIANBH { get; set; }
        public virtual DbSet<DM_TIEMNANG> DM_TIEMNANG { get; set; }
        public virtual DbSet<DM_TINHCHIETKHAU> DM_TINHCHIETKHAU { get; set; }
        public virtual DbSet<DM_TINHHUONGGD> DM_TINHHUONGGD { get; set; }
        public virtual DbSet<DM_TINHTHANHPHO> DM_TINHTHANHPHO { get; set; }
        public virtual DbSet<DM_TINHTRANGGD> DM_TINHTRANGGD { get; set; }
        public virtual DbSet<DM_TINHTRANGHONNHAN> DM_TINHTRANGHONNHAN { get; set; }
        public virtual DbSet<DM_TOKHAINHAPKHAU> DM_TOKHAINHAPKHAU { get; set; }
        public virtual DbSet<DM_TRANGTHAI> DM_TRANGTHAI { get; set; }
        public virtual DbSet<DM_TRINHDO> DM_TRINHDO { get; set; }
        public virtual DbSet<DM_VERSION> DM_VERSION { get; set; }
        public virtual DbSet<DM_VERSION1> DM_VERSION1 { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<HT_AUTO_REPORT_DTDTC> HT_AUTO_REPORT_DTDTC { get; set; }
        public virtual DbSet<HT_AUTO_REPORT_KH> HT_AUTO_REPORT_KH { get; set; }
        public virtual DbSet<HT_AUTO_REPORTS> HT_AUTO_REPORTS { get; set; }
        public virtual DbSet<HT_BAOCAO> HT_BAOCAO { get; set; }
        public virtual DbSet<HT_CACMAUBAOCAO> HT_CACMAUBAOCAO { get; set; }
        public virtual DbSet<HT_CFG_FUNC> HT_CFG_FUNC { get; set; }
        public virtual DbSet<HT_CFG_FUNCTION> HT_CFG_FUNCTION { get; set; }
        public virtual DbSet<HT_CHAMNGON> HT_CHAMNGON { get; set; }
        public virtual DbSet<HT_CHART> HT_CHART { get; set; }
        public virtual DbSet<HT_CHART_LAYOUT> HT_CHART_LAYOUT { get; set; }
        public virtual DbSet<HT_CHART_PNL> HT_CHART_PNL { get; set; }
        public virtual DbSet<HT_CONFIG_MCC> HT_CONFIG_MCC { get; set; }
        public virtual DbSet<HT_CONFIG_MCC_THIETLAPCA> HT_CONFIG_MCC_THIETLAPCA { get; set; }
        public virtual DbSet<HT_CONFIG_NGAYLAMBU> HT_CONFIG_NGAYLAMBU { get; set; }
        public virtual DbSet<HT_CONFIG_VAL_BY_DM> HT_CONFIG_VAL_BY_DM { get; set; }
        public virtual DbSet<HT_CONGCU_TIMKIEM> HT_CONGCU_TIMKIEM { get; set; }
        public virtual DbSet<HT_GRIDEX_VISIBEL> HT_GRIDEX_VISIBEL { get; set; }
        public virtual DbSet<HT_HETHONG> HT_HETHONG { get; set; }
        public virtual DbSet<HT_KHAIBAO> HT_KHAIBAO { get; set; }
        public virtual DbSet<HT_KHAIBAO_KHACHHANG_REG> HT_KHAIBAO_KHACHHANG_REG { get; set; }
        public virtual DbSet<HT_LAYOUT_FIND> HT_LAYOUT_FIND { get; set; }
        public virtual DbSet<HT_LAYOUT_GRID> HT_LAYOUT_GRID { get; set; }
        public virtual DbSet<HT_LAYOUT_TAB> HT_LAYOUT_TAB { get; set; }
        public virtual DbSet<HT_MAUBAOCAO> HT_MAUBAOCAO { get; set; }
        public virtual DbSet<HT_MENU_EXP> HT_MENU_EXP { get; set; }
        public virtual DbSet<HT_MenuList> HT_MenuList { get; set; }
        public virtual DbSet<HT_NGUOIDUYET> HT_NGUOIDUYET { get; set; }
        public virtual DbSet<HT_NHATKYLOGIN> HT_NHATKYLOGIN { get; set; }
        public virtual DbSet<HT_NHOMBAOCAO> HT_NHOMBAOCAO { get; set; }
        public virtual DbSet<HT_NUMBER_PHONE> HT_NUMBER_PHONE { get; set; }
        public virtual DbSet<HT_REPORTS> HT_REPORTS { get; set; }
        public virtual DbSet<HT_REPORTS_SIGN> HT_REPORTS_SIGN { get; set; }
        public virtual DbSet<HT_SQL> HT_SQL { get; set; }
        public virtual DbSet<HT_TABLES_COLUMN> HT_TABLES_COLUMN { get; set; }
        public virtual DbSet<HT_THUMAU> HT_THUMAU { get; set; }
        public virtual DbSet<HT_TYGIA> HT_TYGIA { get; set; }
        public virtual DbSet<HT_UPDATE_DATA> HT_UPDATE_DATA { get; set; }
        public virtual DbSet<HT_UPDATE_DATA_DETAIL> HT_UPDATE_DATA_DETAIL { get; set; }
        public virtual DbSet<ID_PHUONGTHUC_GD> ID_PHUONGTHUC_GD { get; set; }
        public virtual DbSet<KT_BCTC_CanDoiKeToan> KT_BCTC_CanDoiKeToan { get; set; }
        public virtual DbSet<KT_BCTC_KQKD> KT_BCTC_KQKD { get; set; }
        public virtual DbSet<KT_BCTC_LCTT> KT_BCTC_LCTT { get; set; }
        public virtual DbSet<PQ_DANHMUC> PQ_DANHMUC { get; set; }
        public virtual DbSet<PQ_FORM_CAPTION> PQ_FORM_CAPTION { get; set; }
        public virtual DbSet<PQ_FORM_DETAIL> PQ_FORM_DETAIL { get; set; }
        public virtual DbSet<PQ_MENU> PQ_MENU { get; set; }
        public virtual DbSet<PQ_NGUOIDUNG> PQ_NGUOIDUNG { get; set; }
        public virtual DbSet<PQ_NGUOIDUNG_EMAIL> PQ_NGUOIDUNG_EMAIL { get; set; }
        public virtual DbSet<PQ_NGUOIDUNG_NHOM> PQ_NGUOIDUNG_NHOM { get; set; }
        public virtual DbSet<PQ_PANEL> PQ_PANEL { get; set; }
        public virtual DbSet<PQ_TAB> PQ_TAB { get; set; }
        public virtual DbSet<PQ_TOOLBAR> PQ_TOOLBAR { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<sysreplserver> sysreplservers { get; set; }
        public virtual DbSet<TH_BANGTINH> TH_BANGTINH { get; set; }
        public virtual DbSet<TH_BANGTINH_SP_PB> TH_BANGTINH_SP_PB { get; set; }
        public virtual DbSet<TH_BANGTINH_SP_TINH> TH_BANGTINH_SP_TINH { get; set; }
        public virtual DbSet<TH_BAOGIA> TH_BAOGIA { get; set; }
        public virtual DbSet<TH_BAOGIA_FILE> TH_BAOGIA_FILE { get; set; }
        public virtual DbSet<TH_BAOGIA_SP> TH_BAOGIA_SP { get; set; }
        public virtual DbSet<TH_BAOGIA_SP_CAUTHANH> TH_BAOGIA_SP_CAUTHANH { get; set; }
        public virtual DbSet<TH_BTGT> TH_BTGT { get; set; }
        public virtual DbSet<TH_BTGT_HIS> TH_BTGT_HIS { get; set; }
        public virtual DbSet<TH_BTGT_PB> TH_BTGT_PB { get; set; }
        public virtual DbSet<TH_BTGT_PB_HIS> TH_BTGT_PB_HIS { get; set; }
        public virtual DbSet<TH_BTGT_SP> TH_BTGT_SP { get; set; }
        public virtual DbSet<TH_BTGT_SP_HIS> TH_BTGT_SP_HIS { get; set; }
        public virtual DbSet<TH_CANDOIKHO> TH_CANDOIKHO { get; set; }
        public virtual DbSet<TH_CHAMCONG> TH_CHAMCONG { get; set; }
        public virtual DbSet<TH_CHITIEN> TH_CHITIEN { get; set; }
        public virtual DbSet<TH_DUBAO_20150323> TH_DUBAO_20150323 { get; set; }
        public virtual DbSet<TH_DUBAO_REPORTS> TH_DUBAO_REPORTS { get; set; }
        public virtual DbSet<TH_DUBAO_SANPHAM_20150323> TH_DUBAO_SANPHAM_20150323 { get; set; }
        public virtual DbSet<TH_DUBAO_SANPHAM_CAUTHANH> TH_DUBAO_SANPHAM_CAUTHANH { get; set; }
        public virtual DbSet<TH_EMAIL> TH_EMAIL { get; set; }
        public virtual DbSet<TH_EMAIL_DTDTC> TH_EMAIL_DTDTC { get; set; }
        public virtual DbSet<TH_EMAIL_FILE> TH_EMAIL_FILE { get; set; }
        public virtual DbSet<TH_EMAIL_KH> TH_EMAIL_KH { get; set; }
        public virtual DbSet<TH_GHICONGNO> TH_GHICONGNO { get; set; }
        public virtual DbSet<TH_GIAODICH_FILE> TH_GIAODICH_FILE { get; set; }
        public virtual DbSet<TH_HENLICH> TH_HENLICH { get; set; }
        public virtual DbSet<TH_HENLICH_FILE> TH_HENLICH_FILE { get; set; }
        public virtual DbSet<TH_HESOLUONG> TH_HESOLUONG { get; set; }
        public virtual DbSet<TH_HOPDONG_FILE> TH_HOPDONG_FILE { get; set; }
        public virtual DbSet<TH_HOPDONG_SP_CAUTHANH> TH_HOPDONG_SP_CAUTHANH { get; set; }
        public virtual DbSet<TH_HOPDONG_SPPT> TH_HOPDONG_SPPT { get; set; }
        public virtual DbSet<TH_HOSOKHACHHANG_CN> TH_HOSOKHACHHANG_CN { get; set; }
        public virtual DbSet<TH_HOSOKHACHHANG1> TH_HOSOKHACHHANG1 { get; set; }
        public virtual DbSet<TH_HOSONHANVIEN> TH_HOSONHANVIEN { get; set; }
        public virtual DbSet<TH_KEHOACH_NTH> TH_KEHOACH_NTH { get; set; }
        public virtual DbSet<TH_KEHOACH_SANPHAM> TH_KEHOACH_SANPHAM { get; set; }
        public virtual DbSet<TH_KETCHUYEN> TH_KETCHUYEN { get; set; }
        public virtual DbSet<TH_KETCHUYEN_TK> TH_KETCHUYEN_TK { get; set; }
        public virtual DbSet<TH_KHAUHAO_S1> TH_KHAUHAO_S1 { get; set; }
        public virtual DbSet<TH_KHOTON> TH_KHOTON { get; set; }
        public virtual DbSet<TH_MCC_DB> TH_MCC_DB { get; set; }
        public virtual DbSet<TH_MCC_DB_THO> TH_MCC_DB_THO { get; set; }
        public virtual DbSet<TH_NHANTHU> TH_NHANTHU { get; set; }
        public virtual DbSet<TH_NHANTHU_DTDTC> TH_NHANTHU_DTDTC { get; set; }
        public virtual DbSet<TH_NHANTHU_FILE> TH_NHANTHU_FILE { get; set; }
        public virtual DbSet<TH_NHANTHU_KH> TH_NHANTHU_KH { get; set; }
        public virtual DbSet<TH_NHAPHANG> TH_NHAPHANG { get; set; }
        public virtual DbSet<TH_NHAPHANG_FILE> TH_NHAPHANG_FILE { get; set; }
        public virtual DbSet<TH_NHAPHANG_FILE_HIS> TH_NHAPHANG_FILE_HIS { get; set; }
        public virtual DbSet<TH_NHAPHANG_HIS> TH_NHAPHANG_HIS { get; set; }
        public virtual DbSet<TH_NHAPHANG_SP> TH_NHAPHANG_SP { get; set; }
        public virtual DbSet<TH_NHAPHANG_SP_LOT> TH_NHAPHANG_SP_LOT { get; set; }
        public virtual DbSet<TH_REG_KHACHHANG> TH_REG_KHACHHANG { get; set; }
        public virtual DbSet<TH_SANPHAM> TH_SANPHAM { get; set; }
        public virtual DbSet<TH_SANPHAM_CT> TH_SANPHAM_CT { get; set; }
        public virtual DbSet<TH_SANPHAM_DONVI> TH_SANPHAM_DONVI { get; set; }
        public virtual DbSet<TH_SANPHAM_FILE> TH_SANPHAM_FILE { get; set; }
        public virtual DbSet<TH_SANPHAM_SR> TH_SANPHAM_SR { get; set; }
        public virtual DbSet<TH_SANPHAM_TSCD> TH_SANPHAM_TSCD { get; set; }
        public virtual DbSet<TH_SMS> TH_SMS { get; set; }
        public virtual DbSet<TH_SMS_DTDTC> TH_SMS_DTDTC { get; set; }
        public virtual DbSet<TH_SMS_KH> TH_SMS_KH { get; set; }
        public virtual DbSet<TH_SMS_NHAN> TH_SMS_NHAN { get; set; }
        public virtual DbSet<TH_SP_KHAUHAO> TH_SP_KHAUHAO { get; set; }
        public virtual DbSet<TH_THIETLAPCA> TH_THIETLAPCA { get; set; }
        public virtual DbSet<TH_THONGKE> TH_THONGKE { get; set; }
        public virtual DbSet<TH_THUTIEN_HIS> TH_THUTIEN_HIS { get; set; }
        public virtual DbSet<TH_XUATHANG> TH_XUATHANG { get; set; }
        public virtual DbSet<TH_XUATHANG_FILE> TH_XUATHANG_FILE { get; set; }
        public virtual DbSet<TH_XUATHANG_FILE_HIS> TH_XUATHANG_FILE_HIS { get; set; }
        public virtual DbSet<TH_XUATHANG_HIS> TH_XUATHANG_HIS { get; set; }
        public virtual DbSet<TH_XUATHANG_SP> TH_XUATHANG_SP { get; set; }
        public virtual DbSet<TH_XUATHANG_SP_CAUTHANH> TH_XUATHANG_SP_CAUTHANH { get; set; }
        public virtual DbSet<TH_XUATHANG_SP_LOT> TH_XUATHANG_SP_LOT { get; set; }
        public virtual DbSet<tmp_henlich> tmp_henlich { get; set; }
        public virtual DbSet<DM_DTTC> DM_DTTC { get; set; }
        public virtual DbSet<DM_LOAITHUTIEN> DM_LOAITHUTIEN { get; set; }
        public virtual DbSet<TH_GIAODICH> TH_GIAODICH { get; set; }
        public virtual DbSet<TH_HOSOKHACHHANG> TH_HOSOKHACHHANG { get; set; }
        public virtual DbSet<TH_THUTIEN> TH_THUTIEN { get; set; }
        public virtual DbSet<TH_HOPDONG> TH_HOPDONG { get; set; }
        public virtual DbSet<DM_LOAIHOPDONG> DM_LOAIHOPDONG { get; set; }
        public virtual DbSet<DM_VUNG> DM_VUNG { get; set; }
        public virtual DbSet<TH_DUBAO> TH_DUBAO { get; set; }
    
        public virtual ObjectResult<APAX_GETDANHSACHHOCSINH_Result> APAX_GETDANHSACHHOCSINH(string sEARCH, string taiKhoan, Nullable<int> trungTam, Nullable<int> chuongTrinh, Nullable<int> pageSize, Nullable<int> pageNumber)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var trungTamParameter = trungTam.HasValue ?
                new ObjectParameter("TrungTam", trungTam) :
                new ObjectParameter("TrungTam", typeof(int));
    
            var chuongTrinhParameter = chuongTrinh.HasValue ?
                new ObjectParameter("ChuongTrinh", chuongTrinh) :
                new ObjectParameter("ChuongTrinh", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_GETDANHSACHHOCSINH_Result>("APAX_GETDANHSACHHOCSINH", sEARCHParameter, taiKhoanParameter, trungTamParameter, chuongTrinhParameter, pageSizeParameter, pageNumberParameter);
        }
    
        public virtual ObjectResult<APAX_GETDANHSACHHOCSINH_TOTAL_Result> APAX_GETDANHSACHHOCSINH_TOTAL(string sEARCH, string taiKhoan, Nullable<int> trungTam, Nullable<int> chuongTrinh)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var trungTamParameter = trungTam.HasValue ?
                new ObjectParameter("TrungTam", trungTam) :
                new ObjectParameter("TrungTam", typeof(int));
    
            var chuongTrinhParameter = chuongTrinh.HasValue ?
                new ObjectParameter("ChuongTrinh", chuongTrinh) :
                new ObjectParameter("ChuongTrinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_GETDANHSACHHOCSINH_TOTAL_Result>("APAX_GETDANHSACHHOCSINH_TOTAL", sEARCHParameter, taiKhoanParameter, trungTamParameter, chuongTrinhParameter);
        }
    
        public virtual ObjectResult<SP_APAX_DANHSACHCHUONGTRINH_Result> SP_APAX_DANHSACHCHUONGTRINH(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_DANHSACHCHUONGTRINH_Result>("SP_APAX_DANHSACHCHUONGTRINH", keyParameter);
        }
    
        public virtual ObjectResult<SP_APAX_HOCSINHDADANGKYCHUAXEPLOP_Result> SP_APAX_HOCSINHDADANGKYCHUAXEPLOP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_HOCSINHDADANGKYCHUAXEPLOP_Result>("SP_APAX_HOCSINHDADANGKYCHUAXEPLOP");
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHHOCSINH_Result> SP_APAX_GETDANHSACHHOCSINH(Nullable<int> key)
        {
            var keyParameter = key.HasValue ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHHOCSINH_Result>("SP_APAX_GETDANHSACHHOCSINH", keyParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHCHUONGTRINH_Result> SP_APAX_GETDANHSACHCHUONGTRINH(string chuongTrinh)
        {
            var chuongTrinhParameter = chuongTrinh != null ?
                new ObjectParameter("ChuongTrinh", chuongTrinh) :
                new ObjectParameter("ChuongTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHCHUONGTRINH_Result>("SP_APAX_GETDANHSACHCHUONGTRINH", chuongTrinhParameter);
        }
    
        public virtual ObjectResult<SP_APAX_DANHSACHHOCSINHGIAODICH_Result> SP_APAX_DANHSACHHOCSINHGIAODICH(Nullable<int> hOSOKHACHHANG)
        {
            var hOSOKHACHHANGParameter = hOSOKHACHHANG.HasValue ?
                new ObjectParameter("HOSOKHACHHANG", hOSOKHACHHANG) :
                new ObjectParameter("HOSOKHACHHANG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_DANHSACHHOCSINHGIAODICH_Result>("SP_APAX_DANHSACHHOCSINHGIAODICH", hOSOKHACHHANGParameter);
        }
    
        public virtual ObjectResult<SP_APAX_LICHSUDANGKY_Result> SP_APAX_LICHSUDANGKY(Nullable<int> hocVien)
        {
            var hocVienParameter = hocVien.HasValue ?
                new ObjectParameter("HocVien", hocVien) :
                new ObjectParameter("HocVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_LICHSUDANGKY_Result>("SP_APAX_LICHSUDANGKY", hocVienParameter);
        }
    
        public virtual ObjectResult<APAX_TIMKIEM_LOPHOC_Result> APAX_TIMKIEM_LOPHOC(string tENTRUNGTAM, string cHUONGTRINH, string taikhoan)
        {
            var tENTRUNGTAMParameter = tENTRUNGTAM != null ?
                new ObjectParameter("TENTRUNGTAM", tENTRUNGTAM) :
                new ObjectParameter("TENTRUNGTAM", typeof(string));
    
            var cHUONGTRINHParameter = cHUONGTRINH != null ?
                new ObjectParameter("CHUONGTRINH", cHUONGTRINH) :
                new ObjectParameter("CHUONGTRINH", typeof(string));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_TIMKIEM_LOPHOC_Result>("APAX_TIMKIEM_LOPHOC", tENTRUNGTAMParameter, cHUONGTRINHParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHXEPLOP_Result> SP_APAX_GETDANHSACHXEPLOP(Nullable<int> trungTam, Nullable<int> chuongTrinh, string taiKhoan)
        {
            var trungTamParameter = trungTam.HasValue ?
                new ObjectParameter("TrungTam", trungTam) :
                new ObjectParameter("TrungTam", typeof(int));
    
            var chuongTrinhParameter = chuongTrinh.HasValue ?
                new ObjectParameter("ChuongTrinh", chuongTrinh) :
                new ObjectParameter("ChuongTrinh", typeof(int));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHXEPLOP_Result>("SP_APAX_GETDANHSACHXEPLOP", trungTamParameter, chuongTrinhParameter, taiKhoanParameter);
        }
    
        public virtual ObjectResult<APAX_NHANSU_THEOTRUNGTAM_Result> APAX_NHANSU_THEOTRUNGTAM(Nullable<int> mATRUNGTAM, string vITRI)
        {
            var mATRUNGTAMParameter = mATRUNGTAM.HasValue ?
                new ObjectParameter("MATRUNGTAM", mATRUNGTAM) :
                new ObjectParameter("MATRUNGTAM", typeof(int));
    
            var vITRIParameter = vITRI != null ?
                new ObjectParameter("VITRI", vITRI) :
                new ObjectParameter("VITRI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_NHANSU_THEOTRUNGTAM_Result>("APAX_NHANSU_THEOTRUNGTAM", mATRUNGTAMParameter, vITRIParameter);
        }
    
        public virtual ObjectResult<SP_APAX_DANHSACHTRUNGTAMTHEOTAIKHOAN_Result> SP_APAX_DANHSACHTRUNGTAMTHEOTAIKHOAN(string taiKhoan)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_DANHSACHTRUNGTAMTHEOTAIKHOAN_Result>("SP_APAX_DANHSACHTRUNGTAMTHEOTAIKHOAN", taiKhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_HOSOHOCVIEN_Result> SP_APAX_HOSOHOCVIEN(string taikhoan)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_HOSOHOCVIEN_Result>("SP_APAX_HOSOHOCVIEN", taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_TIMDANHSACHHOCSINH_Result> SP_APAX_TIMDANHSACHHOCSINH(string key, string taikhoan)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_TIMDANHSACHHOCSINH_Result>("SP_APAX_TIMDANHSACHHOCSINH", keyParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<string> sp_APAX_TaoMaKhachHang(string loai)
        {
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_APAX_TaoMaKhachHang", loaiParameter);
        }
    
        public virtual ObjectResult<SP_APAX_TIMKIEM_DANGKYHOC_CHUAXEPLOP_Result> SP_APAX_TIMKIEM_DANGKYHOC_CHUAXEPLOP(string key, Nullable<int> iD, string taikhoan)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_TIMKIEM_DANGKYHOC_CHUAXEPLOP_Result>("SP_APAX_TIMKIEM_DANGKYHOC_CHUAXEPLOP", keyParameter, iDParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_DANHSACHDAXEPLOP_Result> SP_APAX_DANHSACHDAXEPLOP(string key, string taikhoan)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_DANHSACHDAXEPLOP_Result>("SP_APAX_DANHSACHDAXEPLOP", keyParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_DANHSACHLOP_Result> SP_APAX_DANHSACHLOP(Nullable<int> trungTam, Nullable<int> lopCu, string taikhoan)
        {
            var trungTamParameter = trungTam.HasValue ?
                new ObjectParameter("TrungTam", trungTam) :
                new ObjectParameter("TrungTam", typeof(int));
    
            var lopCuParameter = lopCu.HasValue ?
                new ObjectParameter("LopCu", lopCu) :
                new ObjectParameter("LopCu", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_DANHSACHLOP_Result>("SP_APAX_DANHSACHLOP", trungTamParameter, lopCuParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_DANHSACHTRUNGTAM_Result> SP_APAX_DANHSACHTRUNGTAM(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_DANHSACHTRUNGTAM_Result>("SP_APAX_DANHSACHTRUNGTAM", keyParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHDAXEPLOPCANCHUYEN_Result> SP_APAX_GETDANHSACHDAXEPLOPCANCHUYEN(Nullable<int> khachHang, Nullable<int> lopHoc)
        {
            var khachHangParameter = khachHang.HasValue ?
                new ObjectParameter("KhachHang", khachHang) :
                new ObjectParameter("KhachHang", typeof(int));
    
            var lopHocParameter = lopHoc.HasValue ?
                new ObjectParameter("LopHoc", lopHoc) :
                new ObjectParameter("LopHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHDAXEPLOPCANCHUYEN_Result>("SP_APAX_GETDANHSACHDAXEPLOPCANCHUYEN", khachHangParameter, lopHocParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHLOP_Result> SP_APAX_GETDANHSACHLOP(Nullable<int> keHoach)
        {
            var keHoachParameter = keHoach.HasValue ?
                new ObjectParameter("KeHoach", keHoach) :
                new ObjectParameter("KeHoach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHLOP_Result>("SP_APAX_GETDANHSACHLOP", keHoachParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHLOPHOC_Result> SP_APAX_GETDANHSACHLOPHOC(Nullable<int> key)
        {
            var keyParameter = key.HasValue ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHLOPHOC_Result>("SP_APAX_GETDANHSACHLOPHOC", keyParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHTRUNGTAM_Result> SP_APAX_GETDANHSACHTRUNGTAM(Nullable<int> trungTam)
        {
            var trungTamParameter = trungTam.HasValue ?
                new ObjectParameter("TrungTam", trungTam) :
                new ObjectParameter("TrungTam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHTRUNGTAM_Result>("SP_APAX_GETDANHSACHTRUNGTAM", trungTamParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GRIDHOCVIENDABAOLUU_Result> SP_APAX_GRIDHOCVIENDABAOLUU(Nullable<int> khachHang, Nullable<int> lopHoc, string taikhoan)
        {
            var khachHangParameter = khachHang.HasValue ?
                new ObjectParameter("KhachHang", khachHang) :
                new ObjectParameter("KhachHang", typeof(int));
    
            var lopHocParameter = lopHoc.HasValue ?
                new ObjectParameter("LopHoc", lopHoc) :
                new ObjectParameter("LopHoc", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GRIDHOCVIENDABAOLUU_Result>("SP_APAX_GRIDHOCVIENDABAOLUU", khachHangParameter, lopHocParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SoBuoiDaBaoLuu(Nullable<int> maKhachHang, Nullable<int> keHoach, Nullable<int> a_TH_DUBAO)
        {
            var maKhachHangParameter = maKhachHang.HasValue ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(int));
    
            var keHoachParameter = keHoach.HasValue ?
                new ObjectParameter("KeHoach", keHoach) :
                new ObjectParameter("KeHoach", typeof(int));
    
            var a_TH_DUBAOParameter = a_TH_DUBAO.HasValue ?
                new ObjectParameter("A_TH_DUBAO", a_TH_DUBAO) :
                new ObjectParameter("A_TH_DUBAO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SoBuoiDaBaoLuu", maKhachHangParameter, keHoachParameter, a_TH_DUBAOParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHDAXEPLOP_Result> SP_APAX_GETDANHSACHDAXEPLOP(Nullable<int> khachHang, Nullable<int> lopHoc)
        {
            var khachHangParameter = khachHang.HasValue ?
                new ObjectParameter("KhachHang", khachHang) :
                new ObjectParameter("KhachHang", typeof(int));
    
            var lopHocParameter = lopHoc.HasValue ?
                new ObjectParameter("LopHoc", lopHoc) :
                new ObjectParameter("LopHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHDAXEPLOP_Result>("SP_APAX_GETDANHSACHDAXEPLOP", khachHangParameter, lopHocParameter);
        }
    
        public virtual ObjectResult<SP_APAX_TIMKIEM_DANHSACH_DAXEPLOP_Result> SP_APAX_TIMKIEM_DANHSACH_DAXEPLOP(Nullable<int> iD, string taikhoan, Nullable<int> iDHocSinh)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var iDHocSinhParameter = iDHocSinh.HasValue ?
                new ObjectParameter("IDHocSinh", iDHocSinh) :
                new ObjectParameter("IDHocSinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_TIMKIEM_DANHSACH_DAXEPLOP_Result>("SP_APAX_TIMKIEM_DANHSACH_DAXEPLOP", iDParameter, taikhoanParameter, iDHocSinhParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHCHUYENLOPTUTTKHAC_Result> SP_APAX_GETDANHSACHCHUYENLOPTUTTKHAC(string taiKhoan, Nullable<int> duBao)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var duBaoParameter = duBao.HasValue ?
                new ObjectParameter("DuBao", duBao) :
                new ObjectParameter("DuBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHCHUYENLOPTUTTKHAC_Result>("SP_APAX_GETDANHSACHCHUYENLOPTUTTKHAC", taiKhoanParameter, duBaoParameter);
        }
    
        public virtual ObjectResult<SP_DanhSachDeNghiChuyenLop_Result> SP_DanhSachDeNghiChuyenLop(string taiKhoan)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DanhSachDeNghiChuyenLop_Result>("SP_DanhSachDeNghiChuyenLop", taiKhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_CHECKTRUNG_Result> SP_APAX_CHECKTRUNG(string soDienThoai, string tenKhachHang, Nullable<int> a_HOSOKHACHHANG)
        {
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var tenKhachHangParameter = tenKhachHang != null ?
                new ObjectParameter("TenKhachHang", tenKhachHang) :
                new ObjectParameter("TenKhachHang", typeof(string));
    
            var a_HOSOKHACHHANGParameter = a_HOSOKHACHHANG.HasValue ?
                new ObjectParameter("A_HOSOKHACHHANG", a_HOSOKHACHHANG) :
                new ObjectParameter("A_HOSOKHACHHANG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_CHECKTRUNG_Result>("SP_APAX_CHECKTRUNG", soDienThoaiParameter, tenKhachHangParameter, a_HOSOKHACHHANGParameter);
        }
    
        public virtual ObjectResult<SP_APAX_LICHSUTHUTIEN_Result> SP_APAX_LICHSUTHUTIEN(Nullable<int> hocVien, Nullable<int> hopDong, Nullable<int> loai)
        {
            var hocVienParameter = hocVien.HasValue ?
                new ObjectParameter("HocVien", hocVien) :
                new ObjectParameter("HocVien", typeof(int));
    
            var hopDongParameter = hopDong.HasValue ?
                new ObjectParameter("HopDong", hopDong) :
                new ObjectParameter("HopDong", typeof(int));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_LICHSUTHUTIEN_Result>("SP_APAX_LICHSUTHUTIEN", hocVienParameter, hopDongParameter, loaiParameter);
        }
    
        public virtual ObjectResult<APAX_DANHSACH_NHANSU_Result> APAX_DANHSACH_NHANSU(string ma, string trungtam)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var trungtamParameter = trungtam != null ?
                new ObjectParameter("trungtam", trungtam) :
                new ObjectParameter("trungtam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_DANHSACH_NHANSU_Result>("APAX_DANHSACH_NHANSU", maParameter, trungtamParameter);
        }
    
        public virtual ObjectResult<APAX_DANHSACH_NHANSU_leader_Result> APAX_DANHSACH_NHANSU_leader(string trungtam)
        {
            var trungtamParameter = trungtam != null ?
                new ObjectParameter("trungtam", trungtam) :
                new ObjectParameter("trungtam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_DANHSACH_NHANSU_leader_Result>("APAX_DANHSACH_NHANSU_leader", trungtamParameter);
        }
    
        public virtual ObjectResult<APAX_DANGKYHOC_DM_GOIPHI_Result> APAX_DANGKYHOC_DM_GOIPHI(string tENTRUNGTAM, string tENCHUONGTRINH)
        {
            var tENTRUNGTAMParameter = tENTRUNGTAM != null ?
                new ObjectParameter("TENTRUNGTAM", tENTRUNGTAM) :
                new ObjectParameter("TENTRUNGTAM", typeof(string));
    
            var tENCHUONGTRINHParameter = tENCHUONGTRINH != null ?
                new ObjectParameter("TENCHUONGTRINH", tENCHUONGTRINH) :
                new ObjectParameter("TENCHUONGTRINH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_DANGKYHOC_DM_GOIPHI_Result>("APAX_DANGKYHOC_DM_GOIPHI", tENTRUNGTAMParameter, tENCHUONGTRINHParameter);
        }
    
        public virtual ObjectResult<APAX_THONGTIN_HS_DANGKYHOC_Result> APAX_THONGTIN_HS_DANGKYHOC(string mAHOCSINH)
        {
            var mAHOCSINHParameter = mAHOCSINH != null ?
                new ObjectParameter("MAHOCSINH", mAHOCSINH) :
                new ObjectParameter("MAHOCSINH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_THONGTIN_HS_DANGKYHOC_Result>("APAX_THONGTIN_HS_DANGKYHOC", mAHOCSINHParameter);
        }
    
        public virtual ObjectResult<APAX_THONGTIN_HS_GETDANGKYHOC_Result> APAX_THONGTIN_HS_GETDANGKYHOC(Nullable<int> aHOSOKHACHHANG, string key, string taikhoan)
        {
            var aHOSOKHACHHANGParameter = aHOSOKHACHHANG.HasValue ?
                new ObjectParameter("AHOSOKHACHHANG", aHOSOKHACHHANG) :
                new ObjectParameter("AHOSOKHACHHANG", typeof(int));
    
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_THONGTIN_HS_GETDANGKYHOC_Result>("APAX_THONGTIN_HS_GETDANGKYHOC", aHOSOKHACHHANGParameter, keyParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHDACTIVE_Result> SP_APAX_GETDANHSACHDACTIVE(Nullable<int> iD_LYDOTD, Nullable<int> lopHoc, string taiKhoan)
        {
            var iD_LYDOTDParameter = iD_LYDOTD.HasValue ?
                new ObjectParameter("ID_LYDOTD", iD_LYDOTD) :
                new ObjectParameter("ID_LYDOTD", typeof(int));
    
            var lopHocParameter = lopHoc.HasValue ?
                new ObjectParameter("LopHoc", lopHoc) :
                new ObjectParameter("LopHoc", typeof(int));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHDACTIVE_Result>("SP_APAX_GETDANHSACHDACTIVE", iD_LYDOTDParameter, lopHocParameter, taiKhoanParameter);
        }
    
        public virtual ObjectResult<APAX_THONGTIN_GOIPHI_Result> APAX_THONGTIN_GOIPHI(Nullable<int> iD_GOIPHI)
        {
            var iD_GOIPHIParameter = iD_GOIPHI.HasValue ?
                new ObjectParameter("ID_GOIPHI", iD_GOIPHI) :
                new ObjectParameter("ID_GOIPHI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_THONGTIN_GOIPHI_Result>("APAX_THONGTIN_GOIPHI", iD_GOIPHIParameter);
        }
    
        public virtual ObjectResult<APAX_DemNgayConLaiChuyenPhi_Result> APAX_DemNgayConLaiChuyenPhi(string tuNgay, string denNgay, Nullable<int> buoi1, Nullable<int> buoi2, Nullable<int> khuVuc)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var buoi1Parameter = buoi1.HasValue ?
                new ObjectParameter("Buoi1", buoi1) :
                new ObjectParameter("Buoi1", typeof(int));
    
            var buoi2Parameter = buoi2.HasValue ?
                new ObjectParameter("Buoi2", buoi2) :
                new ObjectParameter("Buoi2", typeof(int));
    
            var khuVucParameter = khuVuc.HasValue ?
                new ObjectParameter("KhuVuc", khuVuc) :
                new ObjectParameter("KhuVuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_DemNgayConLaiChuyenPhi_Result>("APAX_DemNgayConLaiChuyenPhi", tuNgayParameter, denNgayParameter, buoi1Parameter, buoi2Parameter, khuVucParameter);
        }
    
        public virtual ObjectResult<APAX_HamLayNgayKetThuc_Result> APAX_HamLayNgayKetThuc(string tuNgay, Nullable<int> buoi1, Nullable<int> buoi2, Nullable<int> soBuoi, Nullable<int> khuVuc)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var buoi1Parameter = buoi1.HasValue ?
                new ObjectParameter("Buoi1", buoi1) :
                new ObjectParameter("Buoi1", typeof(int));
    
            var buoi2Parameter = buoi2.HasValue ?
                new ObjectParameter("Buoi2", buoi2) :
                new ObjectParameter("Buoi2", typeof(int));
    
            var soBuoiParameter = soBuoi.HasValue ?
                new ObjectParameter("SoBuoi", soBuoi) :
                new ObjectParameter("SoBuoi", typeof(int));
    
            var khuVucParameter = khuVuc.HasValue ?
                new ObjectParameter("KhuVuc", khuVuc) :
                new ObjectParameter("KhuVuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_HamLayNgayKetThuc_Result>("APAX_HamLayNgayKetThuc", tuNgayParameter, buoi1Parameter, buoi2Parameter, soBuoiParameter, khuVucParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GRIDLICHSUCHUYENPHI_Result> SP_APAX_GRIDLICHSUCHUYENPHI(Nullable<int> khachHang, string taikhoan)
        {
            var khachHangParameter = khachHang.HasValue ?
                new ObjectParameter("KhachHang", khachHang) :
                new ObjectParameter("KhachHang", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GRIDLICHSUCHUYENPHI_Result>("SP_APAX_GRIDLICHSUCHUYENPHI", khachHangParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<APAX_HamLayNgayKetThucBaoLuu_Result> APAX_HamLayNgayKetThucBaoLuu(string tuNgay, Nullable<int> buoi1, Nullable<int> buoi2, Nullable<int> soBuoi, Nullable<int> khuVuc)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var buoi1Parameter = buoi1.HasValue ?
                new ObjectParameter("Buoi1", buoi1) :
                new ObjectParameter("Buoi1", typeof(int));
    
            var buoi2Parameter = buoi2.HasValue ?
                new ObjectParameter("Buoi2", buoi2) :
                new ObjectParameter("Buoi2", typeof(int));
    
            var soBuoiParameter = soBuoi.HasValue ?
                new ObjectParameter("SoBuoi", soBuoi) :
                new ObjectParameter("SoBuoi", typeof(int));
    
            var khuVucParameter = khuVuc.HasValue ?
                new ObjectParameter("KhuVuc", khuVuc) :
                new ObjectParameter("KhuVuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_HamLayNgayKetThucBaoLuu_Result>("APAX_HamLayNgayKetThucBaoLuu", tuNgayParameter, buoi1Parameter, buoi2Parameter, soBuoiParameter, khuVucParameter);
        }
    
        public virtual ObjectResult<SP_APAX_DANHSACHLOP_XEPLOP_Result> SP_APAX_DANHSACHLOP_XEPLOP(Nullable<int> trungTam, Nullable<int> chuongTrinh, string taikhoan, Nullable<int> key)
        {
            var trungTamParameter = trungTam.HasValue ?
                new ObjectParameter("TrungTam", trungTam) :
                new ObjectParameter("TrungTam", typeof(int));
    
            var chuongTrinhParameter = chuongTrinh.HasValue ?
                new ObjectParameter("ChuongTrinh", chuongTrinh) :
                new ObjectParameter("ChuongTrinh", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var keyParameter = key.HasValue ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_DANHSACHLOP_XEPLOP_Result>("SP_APAX_DANHSACHLOP_XEPLOP", trungTamParameter, chuongTrinhParameter, taikhoanParameter, keyParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GRIDLICHSUCHUYENLOP_Result> SP_APAX_GRIDLICHSUCHUYENLOP(Nullable<int> khachHang, string taikhoan)
        {
            var khachHangParameter = khachHang.HasValue ?
                new ObjectParameter("KhachHang", khachHang) :
                new ObjectParameter("KhachHang", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GRIDLICHSUCHUYENLOP_Result>("SP_APAX_GRIDLICHSUCHUYENLOP", khachHangParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GRIDLICHSUCHUYENTRUNGTAM_Result> SP_APAX_GRIDLICHSUCHUYENTRUNGTAM(Nullable<int> hocVien, string taikhoan)
        {
            var hocVienParameter = hocVien.HasValue ?
                new ObjectParameter("HocVien", hocVien) :
                new ObjectParameter("HocVien", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GRIDLICHSUCHUYENTRUNGTAM_Result>("SP_APAX_GRIDLICHSUCHUYENTRUNGTAM", hocVienParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_LICHSUXEPLOP_Result> SP_APAX_LICHSUXEPLOP(Nullable<int> hOSOKHACHHANG)
        {
            var hOSOKHACHHANGParameter = hOSOKHACHHANG.HasValue ?
                new ObjectParameter("HOSOKHACHHANG", hOSOKHACHHANG) :
                new ObjectParameter("HOSOKHACHHANG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_LICHSUXEPLOP_Result>("SP_APAX_LICHSUXEPLOP", hOSOKHACHHANGParameter);
        }
    
        public virtual ObjectResult<APAX_GETCHITIETHOCSINHBAOLUU_Result> APAX_GETCHITIETHOCSINHBAOLUU(Nullable<int> bAOLUU)
        {
            var bAOLUUParameter = bAOLUU.HasValue ?
                new ObjectParameter("BAOLUU", bAOLUU) :
                new ObjectParameter("BAOLUU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_GETCHITIETHOCSINHBAOLUU_Result>("APAX_GETCHITIETHOCSINHBAOLUU", bAOLUUParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GRIDCHITIETHOCVIENBAOLUU_Result> SP_APAX_GRIDCHITIETHOCVIENBAOLUU(Nullable<int> a_TH_DUBAO)
        {
            var a_TH_DUBAOParameter = a_TH_DUBAO.HasValue ?
                new ObjectParameter("A_TH_DUBAO", a_TH_DUBAO) :
                new ObjectParameter("A_TH_DUBAO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GRIDCHITIETHOCVIENBAOLUU_Result>("SP_APAX_GRIDCHITIETHOCVIENBAOLUU", a_TH_DUBAOParameter);
        }
    
        public virtual ObjectResult<SP_APAX_TIMKIEM_DANHSACH_NHANPHI_Result> SP_APAX_TIMKIEM_DANHSACH_NHANPHI(string taikhoan, Nullable<int> iDHocSinh)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var iDHocSinhParameter = iDHocSinh.HasValue ?
                new ObjectParameter("IDHocSinh", iDHocSinh) :
                new ObjectParameter("IDHocSinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_TIMKIEM_DANHSACH_NHANPHI_Result>("SP_APAX_TIMKIEM_DANHSACH_NHANPHI", taikhoanParameter, iDHocSinhParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GRIDLICHSUTAMDUNG_Result> SP_APAX_GRIDLICHSUTAMDUNG(Nullable<int> khachHang, string taikhoan)
        {
            var khachHangParameter = khachHang.HasValue ?
                new ObjectParameter("KhachHang", khachHang) :
                new ObjectParameter("KhachHang", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GRIDLICHSUTAMDUNG_Result>("SP_APAX_GRIDLICHSUTAMDUNG", khachHangParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<APAX_DANHSACHLICHSUDUYET_Result> APAX_DANHSACHLICHSUDUYET(Nullable<int> duBao)
        {
            var duBaoParameter = duBao.HasValue ?
                new ObjectParameter("DuBao", duBao) :
                new ObjectParameter("DuBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_DANHSACHLICHSUDUYET_Result>("APAX_DANHSACHLICHSUDUYET", duBaoParameter);
        }
    
        public virtual ObjectResult<APAX_DANHSACHLICHSUDUYETDANGKYLOP_Result> APAX_DANHSACHLICHSUDUYETDANGKYLOP(Nullable<int> duBao)
        {
            var duBaoParameter = duBao.HasValue ?
                new ObjectParameter("DuBao", duBao) :
                new ObjectParameter("DuBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_DANHSACHLICHSUDUYETDANGKYLOP_Result>("APAX_DANHSACHLICHSUDUYETDANGKYLOP", duBaoParameter);
        }
    
        public virtual ObjectResult<SP_APAX_CHITIETLICHSUDANGKY_Result> SP_APAX_CHITIETLICHSUDANGKY(Nullable<int> j_TH_HOPDONG)
        {
            var j_TH_HOPDONGParameter = j_TH_HOPDONG.HasValue ?
                new ObjectParameter("J_TH_HOPDONG", j_TH_HOPDONG) :
                new ObjectParameter("J_TH_HOPDONG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_CHITIETLICHSUDANGKY_Result>("SP_APAX_CHITIETLICHSUDANGKY", j_TH_HOPDONGParameter);
        }
    
        public virtual ObjectResult<APAX_THONGTIN_XEPLOP_Result> APAX_THONGTIN_XEPLOP(Nullable<int> hocVien)
        {
            var hocVienParameter = hocVien.HasValue ?
                new ObjectParameter("HocVien", hocVien) :
                new ObjectParameter("HocVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_THONGTIN_XEPLOP_Result>("APAX_THONGTIN_XEPLOP", hocVienParameter);
        }
    
        public virtual ObjectResult<SP_APAX_CHITIETHOCSINHNHANHOCPHI_Result> SP_APAX_CHITIETHOCSINHNHANHOCPHI(Nullable<int> iD, string taikhoan)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_CHITIETHOCSINHNHANHOCPHI_Result>("SP_APAX_CHITIETHOCSINHNHANHOCPHI", iDParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_CHITIETLICHSUCHUYENLOP_Result> SP_APAX_CHITIETLICHSUCHUYENLOP(Nullable<int> a_TH_DUBAO)
        {
            var a_TH_DUBAOParameter = a_TH_DUBAO.HasValue ?
                new ObjectParameter("A_TH_DUBAO", a_TH_DUBAO) :
                new ObjectParameter("A_TH_DUBAO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_CHITIETLICHSUCHUYENLOP_Result>("SP_APAX_CHITIETLICHSUCHUYENLOP", a_TH_DUBAOParameter);
        }
    
        public virtual ObjectResult<BAOCAO_APAX_DS_CHOXEPLOP_Result> BAOCAO_APAX_DS_CHOXEPLOP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BAOCAO_APAX_DS_CHOXEPLOP_Result>("BAOCAO_APAX_DS_CHOXEPLOP");
        }
    
        public virtual ObjectResult<BAOCAO_APAX_DS_HOCSINH_Result> BAOCAO_APAX_DS_HOCSINH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BAOCAO_APAX_DS_HOCSINH_Result>("BAOCAO_APAX_DS_HOCSINH");
        }
    
        public virtual ObjectResult<BAOCAO_APAX_DS_HOCSINHMOI_Result> BAOCAO_APAX_DS_HOCSINHMOI(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BAOCAO_APAX_DS_HOCSINHMOI_Result>("BAOCAO_APAX_DS_HOCSINHMOI", dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<BAOCAO_APAX_DS_WITHDRAW_Result> BAOCAO_APAX_DS_WITHDRAW(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BAOCAO_APAX_DS_WITHDRAW_Result>("BAOCAO_APAX_DS_WITHDRAW", dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETCHITIETHOCSINHCHUYENNHANPHI_Result> SP_APAX_GETCHITIETHOCSINHCHUYENNHANPHI(string taiKhoan, Nullable<int> duBao)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var duBaoParameter = duBao.HasValue ?
                new ObjectParameter("DuBao", duBao) :
                new ObjectParameter("DuBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETCHITIETHOCSINHCHUYENNHANPHI_Result>("SP_APAX_GETCHITIETHOCSINHCHUYENNHANPHI", taiKhoanParameter, duBaoParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETDANHSACHCHUYENPHIDUYET_Result> SP_APAX_GETDANHSACHCHUYENPHIDUYET(string taiKhoan, Nullable<int> duBao)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var duBaoParameter = duBao.HasValue ?
                new ObjectParameter("DuBao", duBao) :
                new ObjectParameter("DuBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETDANHSACHCHUYENPHIDUYET_Result>("SP_APAX_GETDANHSACHCHUYENPHIDUYET", taiKhoanParameter, duBaoParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GRIDLICHSUCHUYENPHI1_Result> SP_APAX_GRIDLICHSUCHUYENPHI1(Nullable<int> khachHang, string taikhoan)
        {
            var khachHangParameter = khachHang.HasValue ?
                new ObjectParameter("KhachHang", khachHang) :
                new ObjectParameter("KhachHang", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GRIDLICHSUCHUYENPHI1_Result>("SP_APAX_GRIDLICHSUCHUYENPHI1", khachHangParameter, taikhoanParameter);
        }
    
        public virtual ObjectResult<APAX_GetTrungTamBayUserName_Result> APAX_GetTrungTamBayUserName(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_GetTrungTamBayUserName_Result>("APAX_GetTrungTamBayUserName", userNameParameter);
        }
    
        public virtual ObjectResult<SP_APAX_DANHSACHLOPCHUYENTT_Result> SP_APAX_DANHSACHLOPCHUYENTT(string taikhoan)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_DANHSACHLOPCHUYENTT_Result>("SP_APAX_DANHSACHLOPCHUYENTT", taikhoanParameter);
        }
    
        public virtual ObjectResult<SP_APAX_GETCHITIETXEPLOP_Result> SP_APAX_GETCHITIETXEPLOP(string taiKhoan, Nullable<int> duBao)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var duBaoParameter = duBao.HasValue ?
                new ObjectParameter("DuBao", duBao) :
                new ObjectParameter("DuBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_APAX_GETCHITIETXEPLOP_Result>("SP_APAX_GETCHITIETXEPLOP", taiKhoanParameter, duBaoParameter);
        }
    
        public virtual ObjectResult<SP_DanhSachDeNghiTiepNhan_Result> SP_DanhSachDeNghiTiepNhan(string taiKhoan)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DanhSachDeNghiTiepNhan_Result>("SP_DanhSachDeNghiTiepNhan", taiKhoanParameter);
        }
    
        public virtual ObjectResult<APAX_DANHSACHLICHSUDUYETTIEPNHANCHUYENLOP_Result> APAX_DANHSACHLICHSUDUYETTIEPNHANCHUYENLOP(Nullable<int> duBao)
        {
            var duBaoParameter = duBao.HasValue ?
                new ObjectParameter("DuBao", duBao) :
                new ObjectParameter("DuBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APAX_DANHSACHLICHSUDUYETTIEPNHANCHUYENLOP_Result>("APAX_DANHSACHLICHSUDUYETTIEPNHANCHUYENLOP", duBaoParameter);
        }
    }
}
