//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_FORM_DETAIL
    {
        public int A_FORM_DETAIL { get; set; }
        public Nullable<int> STT { get; set; }
        public string FORMNAME { get; set; }
        public string OBJECT { get; set; }
        public string CTR_NAME { get; set; }
        public string CTR_CAPTION { get; set; }
        public Nullable<int> TABINDEX { get; set; }
        public string TAG { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public Nullable<bool> VISIBLE { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public Nullable<int> EMPTY { get; set; }
        public string DEFAULTVALUE { get; set; }
        public string NGUOIDUNG { get; set; }
        public string NGUOIDUNGNHOM { get; set; }
    }
}
