//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_MENU
    {
        public int A_MENU { get; set; }
        public string TENMENU { get; set; }
        public string TEXT { get; set; }
        public string TAG { get; set; }
        public Nullable<int> MUC { get; set; }
        public Nullable<int> CHIMUC { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public string NGUOIDUNG { get; set; }
        public string NGUOIDUNGNHOM { get; set; }
    }
}
