//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_NGUOIDUNG_NHOM
    {
        public int A_NGUOIDUNG_NHOM { get; set; }
        public Nullable<int> J_NGUOIDUNG_NHOM { get; set; }
        public Nullable<int> ID_PHONGBAN { get; set; }
        public string TENPHONGBAN { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public string GHICHU { get; set; }
    }
}
