//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_NGUOIDUNG_EMAIL
    {
        public int A_NGUOIDUNG_EMAIL { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public string USEREMAIL { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string SMTPSERVER { get; set; }
        public string SMTPPORT { get; set; }
        public string POPSERVER { get; set; }
        public string POPPORT { get; set; }
        public Nullable<bool> SSL { get; set; }
        public Nullable<bool> POPIMAP { get; set; }
        public Nullable<bool> TUDONGNHANEMAIL { get; set; }
    }
}
