//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_NGUOIDUNG
    {
        public int A_NGUOIDUNG { get; set; }
        public Nullable<int> J_NGUOIDUNG_NHOM { get; set; }
        public int ID_PHONGBAN { get; set; }
        public int ID_DTTC { get; set; }
        public string TENDTTC { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public Nullable<bool> XUATDULIEU { get; set; }
        public byte[] HINHNEN { get; set; }
        public string FONTNAME { get; set; }
        public Nullable<double> FONTSIZE { get; set; }
        public Nullable<int> FORECOLOR { get; set; }
        public Nullable<int> BACKCOLOR { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> QUYEN { get; set; }
        public string QUYENDULIEU { get; set; }
        public string HTMLCHUKY { get; set; }
        public byte[] CHUKY { get; set; }
        public Nullable<int> J_CHINHANH { get; set; }
        public string QUYENCHINHANH { get; set; }
        public string MATKHAU_WEB { get; set; }
    }
}
