//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_PANEL
    {
        public int A_PANEL { get; set; }
        public string PANELNAME { get; set; }
        public string TENHIENTHI { get; set; }
        public string TAG { get; set; }
        public string NGUOIDUNG { get; set; }
    }
}
