//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_TAB
    {
        public int A_TAB { get; set; }
        public string TABNAME { get; set; }
        public string TABHIENTHI { get; set; }
        public string TAG { get; set; }
        public string NGUOIDUNG { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public Nullable<bool> ISMENU { get; set; }
    }
}
