//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_LopHoc
    {
        public int IDLopHoc { get; set; }
        public string TenLopHoc { get; set; }
        public Nullable<int> ChuongTrinh { get; set; }
        public Nullable<int> IDBuoi { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<int> TrungTam { get; set; }
        public Nullable<int> SoBuoi { get; set; }
        public Nullable<int> IDBuoi2 { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    }
}
