//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BAOGIA_FILE
    {
        public int A_BAOGIA_FILE { get; set; }
        public int J_TH_BAOGIA { get; set; }
        public string FILENAME { get; set; }
        public string PATHFILE { get; set; }
        public byte[] IMAGES { get; set; }
    }
}
