//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BTGT_HIS
    {
        public Nullable<int> CHGMAN { get; set; }
        public string CHGMAY { get; set; }
        public Nullable<System.DateTime> CHGDATE { get; set; }
        public int ID_BTGT { get; set; }
        public string MA_BTGT { get; set; }
        public string TEN_BTGT { get; set; }
        public Nullable<int> LANPB { get; set; }
        public Nullable<System.DateTime> NGAYTINH { get; set; }
        public string GHICHU { get; set; }
        public string PHUONGTHUCTINH { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<decimal> TONGDOANHSOBAN { get; set; }
        public Nullable<decimal> TONGCHIPHI { get; set; }
        public Nullable<decimal> TONGGIATRIGOC { get; set; }
        public Nullable<decimal> LOINHUANTAMTINH { get; set; }
        public Nullable<bool> CAPNHATGIA { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHATBQGQ { get; set; }
        public Nullable<bool> MAUBOMCHUAN { get; set; }
        public Nullable<int> ID_DINHKHOAN_NO { get; set; }
        public string GroupFields { get; set; }
        public Nullable<bool> PhanBoGroup { get; set; }
        public Nullable<bool> DoiDau { get; set; }
        public string QUYENDULIEU { get; set; }
        public Nullable<bool> DULIEUNHOM { get; set; }
    }
}
