//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BTGT_SP
    {
        public int ID_BTGT_SP { get; set; }
        public Nullable<int> ID_BTGT { get; set; }
        public string MA_BTGT { get; set; }
        public Nullable<bool> CHON { get; set; }
        public Nullable<int> A_ID_LTH { get; set; }
        public string LOAITHUCHIEN { get; set; }
        public string A_THUCHIEN { get; set; }
        public Nullable<int> A_SANPHAM { get; set; }
        public Nullable<double> SOLUONG { get; set; }
        public Nullable<double> TYLE { get; set; }
        public Nullable<decimal> DONGIABANTE { get; set; }
        public Nullable<decimal> GIATRITHEM { get; set; }
        public Nullable<decimal> DONGIAMOI { get; set; }
        public Nullable<int> THUEVAT { get; set; }
        public Nullable<int> CHIETKHAU { get; set; }
        public string TENDONVITINH { get; set; }
        public Nullable<double> TYGIA { get; set; }
        public string GIATRITHEMN { get; set; }
        public Nullable<int> ID_DINHKHOAN_NO { get; set; }
        public Nullable<int> ID_DINHKHOAN_CO { get; set; }
        public Nullable<decimal> HESO { get; set; }
        public Nullable<decimal> THANHTIENTHEM { get; set; }
        public string ID_BTGT_LASTEST { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    }
}
