//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BAOGIA
    {
        public int A_TH_BAOGIA { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> ID_MUCDICH { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public Nullable<int> J_DTDTC { get; set; }
        public string SOBAOGIA { get; set; }
        public string TENBAOGIA { get; set; }
        public string TIEUDEBAOGIA { get; set; }
        public string CAUCHAO { get; set; }
        public string GHICHUBAOGIA { get; set; }
        public string DUPHONG1 { get; set; }
        public string DUPHONG2 { get; set; }
        public string DUPHONG3 { get; set; }
        public System.DateTime NGAYBAOGIA { get; set; }
        public Nullable<System.DateTime> NGAYHIEULUC { get; set; }
        public bool DULIEUNHOM { get; set; }
        public Nullable<decimal> TYGIAVND { get; set; }
        public Nullable<decimal> TONGTIENCK { get; set; }
        public Nullable<decimal> TONGTIENBAOGIA { get; set; }
        public Nullable<bool> CHIETKHAUPT { get; set; }
        public Nullable<bool> NHIEUCOTGIA { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string QUYENDULIEU { get; set; }
        public string DANHSACHDUYET { get; set; }
        public Nullable<bool> CHECKTYGIA { get; set; }
        public string SOTANGLUYKEBG { get; set; }
        public Nullable<decimal> CKTONGTIENBG { get; set; }
        public Nullable<bool> CHIETKHAUPTTONG { get; set; }
        public Nullable<decimal> TONGTIENBAOGIA_CK { get; set; }
        public Nullable<bool> TRANGTHAIDK { get; set; }
        public Nullable<bool> TRANGTHAIDONGHP { get; set; }
        public Nullable<int> SOBUOI { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<int> ID_KHUVUC { get; set; }
    }
}
