//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BANGTINH_SP_TINH
    {
        public int A_BANGTINH_SP_TINH { get; set; }
        public Nullable<int> J_BANGTINH { get; set; }
        public Nullable<int> J_SANPHAM { get; set; }
        public Nullable<int> J_TH_BAOGIA { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<int> THUEVAT { get; set; }
        public Nullable<decimal> CHIETKHAU { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<decimal> DONGIA1 { get; set; }
        public Nullable<decimal> DONGIA2 { get; set; }
        public Nullable<decimal> DONGIA3 { get; set; }
        public Nullable<decimal> THANHTIEN1 { get; set; }
        public Nullable<decimal> THANHTIEN2 { get; set; }
        public Nullable<decimal> THANHTIEN3 { get; set; }
        public Nullable<decimal> DONGIATHEM1 { get; set; }
        public Nullable<decimal> DONGIATHEM2 { get; set; }
        public Nullable<decimal> DONGIATHEM3 { get; set; }
        public Nullable<decimal> DONGIATHEM4 { get; set; }
        public Nullable<decimal> DONGIATHEM5 { get; set; }
        public Nullable<decimal> DONGIAMOI { get; set; }
        public Nullable<decimal> THANHTIENMOI { get; set; }
        public string DINHKHOANCO { get; set; }
        public string DINHKHOANNO { get; set; }
        public string DINHKHOANNOPHANBO { get; set; }
        public Nullable<int> J_TH_CHITIEN { get; set; }
        public Nullable<int> J_TH_THUTIEN { get; set; }
        public string MALOT { get; set; }
    }
}
