//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BANGTINH
    {
        public int A_BANGTINH { get; set; }
        public Nullable<int> J_HOSOKHACHHANG { get; set; }
        public string MABANGTINH { get; set; }
        public string TENBANGTINH { get; set; }
        public string GHICHUBANGTINH { get; set; }
        public Nullable<System.DateTime> NGAYBANGTINH { get; set; }
        public Nullable<bool> DULIEUNHOM { get; set; }
        public string QUYENDULIEU { get; set; }
        public Nullable<bool> PHANBOPHANCHAM { get; set; }
        public Nullable<decimal> TONGIATRIPHANBO { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> ID_LOAIBANGTINH { get; set; }
        public Nullable<int> ID_PHUONGPHAPTINH { get; set; }
        public Nullable<bool> CAPNHATPHANBO { get; set; }
    }
}
