//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BANGTINH_SP_PB
    {
        public int A_BANGTINH_SP_PB { get; set; }
        public int J_BANGTINH { get; set; }
        public int J_SANPHAM { get; set; }
        public Nullable<int> J_TH_BAOGIA { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
        public Nullable<int> J_TH_THUTIEN { get; set; }
        public Nullable<int> J_TH_CHITIEN { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<decimal> THANHTIENPHANBO { get; set; }
        public Nullable<decimal> THANHTIENCHENH { get; set; }
        public Nullable<decimal> SOLUONGPHANBO { get; set; }
        public Nullable<decimal> SOLUONGCHENH { get; set; }
        public string DINHKHOANNO { get; set; }
        public string DINHKHOANCO { get; set; }
        public string MALOT { get; set; }
    }
}
