//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BTGT_PB_HIS
    {
        public int ID_BTGT_PB { get; set; }
        public Nullable<int> ID_BTGT { get; set; }
        public string MA_BTGT { get; set; }
        public Nullable<bool> CHON { get; set; }
        public Nullable<int> A_ID_LTH { get; set; }
        public string LOAITHUCHIEN { get; set; }
        public string A_THUCHIEN { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIEN { get; set; }
        public string TENKHACHHANG { get; set; }
        public string GHICHU { get; set; }
        public string TENDTTC { get; set; }
        public string A_SANPHAM { get; set; }
        public Nullable<double> SOLUONG { get; set; }
        public Nullable<double> SOLUONGPHANBO { get; set; }
        public Nullable<double> SOLUONGCHENH { get; set; }
        public Nullable<double> PHANTRAM { get; set; }
        public Nullable<double> PHANTRAMPB { get; set; }
        public Nullable<double> PHANTRAMCHENH { get; set; }
        public Nullable<decimal> DONGIABANTE { get; set; }
        public Nullable<int> THUEVAT { get; set; }
        public Nullable<int> CHIETKHAU { get; set; }
        public string TENDONVITINH { get; set; }
        public Nullable<double> TYGIA { get; set; }
        public Nullable<decimal> THANHTIENPHANBO { get; set; }
        public Nullable<long> XUATNHAP { get; set; }
        public Nullable<bool> LOAITINH { get; set; }
        public Nullable<int> ID_DINHKHOAN_NO { get; set; }
        public Nullable<int> ID_DINHKHOAN_CO { get; set; }
        public Nullable<decimal> TONGSOLUONG { get; set; }
        public string ID_BTGT_LASTEST { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    }
}
