//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_BAOLUU
    {
        public int A_BAOLUU { get; set; }
        public Nullable<int> J_HOSOKHACHHANG { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public Nullable<double> SOBUOIBAOLUU { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENGAY { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public Nullable<int> NGUOIDUNG2 { get; set; }
        public Nullable<System.DateTime> NGAY2 { get; set; }
        public Nullable<bool> ISDEL { get; set; }
    }
}
