//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_CHAMCONG
    {
        public int A_MCC { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.TimeSpan> GIOVAO { get; set; }
        public Nullable<System.TimeSpan> GIORA { get; set; }
    }
}
