//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_CANDOIKHO
    {
        public int A_TH_CANDOIKHO { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<int> ID_KHOHANG { get; set; }
        public Nullable<decimal> SOLUONGXUAT { get; set; }
        public Nullable<decimal> SOLUONGNHAP { get; set; }
        public Nullable<decimal> SOLUONGTON { get; set; }
        public int J_SANPHAM { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIEN { get; set; }
        public Nullable<bool> NHAP_XUAT { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
    }
}
