//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_CHITIEN
    {
        public int A_TH_CHITIEN { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_DTDTC { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> ID_LOAIPHIEUCHI { get; set; }
        public Nullable<int> ID_BOPHAN { get; set; }
        public Nullable<int> ID_PHANXUONG { get; set; }
        public Nullable<int> ID_DINHKHOAN_NO { get; set; }
        public Nullable<int> ID_DINHKHOAN_CO { get; set; }
        public string MACHITIEN { get; set; }
        public string SOPHIEUCHI { get; set; }
        public string DUPHONG1 { get; set; }
        public string DUPHONG2 { get; set; }
        public Nullable<decimal> TONGTIENNONHACUNGCAP { get; set; }
        public Nullable<decimal> SOTIENCHI { get; set; }
        public Nullable<decimal> TONGTIENCHITIEN { get; set; }
        public Nullable<decimal> TONGTIENPHAICHI { get; set; }
        public Nullable<decimal> TONGCONGTIEN { get; set; }
        public Nullable<decimal> DUNODAUKY { get; set; }
        public Nullable<decimal> DUNOCUOIKY { get; set; }
        public string GHICHUCHITIEN { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIEN { get; set; }
        public Nullable<bool> DULIEUNHOM { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<int> ID_LOAITIENCHI { get; set; }
        public Nullable<decimal> TYGIA2 { get; set; }
        public Nullable<decimal> TYGIACHI { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string QUYENDULIEU { get; set; }
        public Nullable<decimal> NGUYENTE { get; set; }
    }
}
