//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_DUBAO_REPORTS
    {
        public int A_DUBAO_REPORT { get; set; }
        public Nullable<int> J_TH_DUABO { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<bool> XACNHAN { get; set; }
        public Nullable<int> THUTU { get; set; }
        public byte[] CHUKY { get; set; }
    }
}
