//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_DUBAO_SANPHAM_CAUTHANH
    {
        public int A_DUBAO_SPCAUTHANH { get; set; }
        public Nullable<int> J_TH_DUBAO_SP { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_SANPHAM_ME { get; set; }
        public Nullable<int> J_SANPHAM { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> THUEVAT { get; set; }
        public Nullable<decimal> CHIETKHAU { get; set; }
        public Nullable<decimal> DONGIA1 { get; set; }
        public Nullable<decimal> DONGIA2 { get; set; }
        public Nullable<decimal> DONGIA3 { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public Nullable<int> J_SANPHAM_DTCPSX { get; set; }
        public Nullable<int> J_SANPHAM_KMP { get; set; }
        public Nullable<int> J_SANPHAM_DTTHCP { get; set; }
    }
}
