//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_DIEMDANH
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> THU { get; set; }
        public Nullable<bool> ISDIEMDANH { get; set; }
        public Nullable<bool> NGAYLE { get; set; }
        public Nullable<bool> ISPHEP { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
    }
}
