//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_DANGKYCHUYENPHI
    {
        public int IDCHUYENPHI { get; set; }
        public Nullable<int> HOCSINHCHUYEN { get; set; }
        public Nullable<int> HOCSINHNHAN { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
        public Nullable<int> SOBUOICONLAI { get; set; }
        public Nullable<decimal> PHICONLAI { get; set; }
        public Nullable<bool> DUYETCHUYEN { get; set; }
        public Nullable<int> NGUOIDUYET { get; set; }
        public Nullable<System.DateTime> NGAYDUYET { get; set; }
        public Nullable<int> TH_KEHOACH { get; set; }
        public Nullable<int> CHUONGTRINH { get; set; }
    }
}
