//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_DANGKYCHUYENLOP
    {
        public int IDCHUYENLOP { get; set; }
        public Nullable<int> J_HOSOKHACHHANG { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public Nullable<int> J_KEHOACH1 { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
        public Nullable<int> NGUOIDANGKY { get; set; }
        public Nullable<bool> DUYETDANGKY { get; set; }
        public Nullable<int> NGUOIDUYET { get; set; }
        public Nullable<System.DateTime> NGAYDUYET { get; set; }
        public Nullable<int> NGUOISUADANGKY { get; set; }
        public Nullable<System.DateTime> NGAYSUADANGKY { get; set; }
        public Nullable<bool> ISDEL { get; set; }
    }
}
