//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_DUYETTHUCHIEN
    {
        public int A_DUYET { get; set; }
        public Nullable<int> J_TH_BAOGIA { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
        public Nullable<int> J_TH_THUTIEN { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<int> J_TH_CHITIEN { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> ID_DUYET { get; set; }
        public string YKIENBOSUNG { get; set; }
        public Nullable<System.DateTime> NGAYDUYET { get; set; }
        public string NGUOINHANKETQUA { get; set; }
        public Nullable<int> J_HOSOKHACHHANG { get; set; }
    }
}
