//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_DUBAO_20150323
    {
        public int A_TH_DUBAO { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public int ID_DTTC { get; set; }
        public int J_DTDTC { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> ID_KHANCAP { get; set; }
        public Nullable<int> ID_TIEMNANG { get; set; }
        public Nullable<int> ID_LYDO_NT { get; set; }
        public Nullable<int> ID_LYDO_TD { get; set; }
        public Nullable<int> ID_LYDO_HV { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<int> ID_NHANTHUC { get; set; }
        public Nullable<int> ID_THAIDO { get; set; }
        public Nullable<int> ID_HANHVI { get; set; }
        public Nullable<bool> NHANTHUC { get; set; }
        public Nullable<bool> THAIDO { get; set; }
        public Nullable<bool> HANHVI { get; set; }
        public Nullable<decimal> TYGIAVND { get; set; }
        public Nullable<System.DateTime> NGAYGIAOHANG { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public Nullable<System.DateTime> NGAYLAM { get; set; }
        public string SODONHANG { get; set; }
        public Nullable<decimal> TONGTIEN_CK { get; set; }
        public Nullable<decimal> TONGTIEN_DH { get; set; }
        public Nullable<decimal> TONGCONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> XUATNHAP { get; set; }
        public string DUPHONG1 { get; set; }
        public bool DULIEUNHOM { get; set; }
        public Nullable<bool> CHIETKHAUPT { get; set; }
        public Nullable<bool> NHIEUCOTGIA { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string MAKS { get; set; }
        public string QUYENDULIEU { get; set; }
        public string DANHSACHKHANCAP { get; set; }
        public string DANHSACHGIAOHANG { get; set; }
        public string DANHSACHTHANHTOAN { get; set; }
        public Nullable<bool> CHECKTYGIA { get; set; }
        public string DUPHONG2 { get; set; }
        public string SOTANGLUYKEDB { get; set; }
        public Nullable<decimal> CKTONGTIENDB { get; set; }
        public Nullable<bool> CHIETKHAUPTTONG { get; set; }
        public Nullable<decimal> TONGTIENDUBAO_CK { get; set; }
    }
}
