//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_EMAIL
    {
        public int A_TH_EMAIL { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public Nullable<int> ID_MUCDICH { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> ID_LOAIMAIL { get; set; }
        public string NGUOINHAN { get; set; }
        public string DONGGUICC { get; set; }
        public string DONGGUIBCC { get; set; }
        public Nullable<int> TAIKHOANGUI { get; set; }
        public string TIEUDE { get; set; }
        public Nullable<System.DateTime> NGAYGUI { get; set; }
        public string NOIDUNG { get; set; }
        public bool DULIEUNHOM { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<bool> DOCTHU { get; set; }
        public Nullable<bool> CHECKFILE { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string MAKS { get; set; }
        public byte[] FILENOIDUNGEMAIL { get; set; }
        public string PATHFILE { get; set; }
        public Nullable<bool> THUMAU { get; set; }
        public string HTMLCODE { get; set; }
        public Nullable<int> NUMBEREMAIL { get; set; }
        public Nullable<bool> GUIDICHDANH { get; set; }
        public Nullable<bool> GUICOKIEMSOAT { get; set; }
        public string EMAILCHUAGUI { get; set; }
    }
}
