//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_GIAODICH
    {
        public int A_TH_GIAODICH { get; set; }
        public int J_KHACHHANG { get; set; }
        public Nullable<int> J_HOSODTDTC { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_TH_BAOGIA { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
        public Nullable<int> J_TH_CHITIEN { get; set; }
        public Nullable<int> J_TH_THUTIEN { get; set; }
        public Nullable<int> J_TH_EMAIL { get; set; }
        public Nullable<int> J_TH_SMS { get; set; }
        public Nullable<int> J_TH_NHANTHU { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<int> ID_MUCDICH { get; set; }
        public Nullable<int> ID_PHUONGTHUC_GD { get; set; }
        public Nullable<int> ID_CONGCU { get; set; }
        public string NOIDUNG_GIAODICH { get; set; }
        public string PHANHOI_KHACHHANG { get; set; }
        public string CHOTCACDIEM_THONGNHAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAODICH { get; set; }
        public Nullable<bool> DULIEUNHOM { get; set; }
        public Nullable<int> ID_TINHHUONGD { get; set; }
        public Nullable<int> ID_TINHTRANGGD { get; set; }
        public Nullable<int> ID_NGUONPHANHOI { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string MAKS { get; set; }
        public string QUYENDULIEU { get; set; }
        public string DANHGIA { get; set; }
        public string GHICHU { get; set; }
        public string DUPHONG1 { get; set; }
        public Nullable<int> ID_TIEMNANG { get; set; }
    }
}
