//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_GHICONGNO
    {
        public int A_GHICONGNO { get; set; }
        public int J_TH_HOSOKHACHHANG { get; set; }
        public int ID_LOAITHUCHIEN { get; set; }
        public int J_THUCHIEN { get; set; }
        public int ID_DINHKHOAN_NO { get; set; }
        public int ID_DINHKHOAN_CO { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIEN { get; set; }
        public Nullable<int> J_SANPHAM { get; set; }
    }
}
