//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_HOSOKHACHHANG1
    {
        public int A_HOSOKHACHHANG { get; set; }
        public string MAKH { get; set; }
        public string TENKHACHHANG { get; set; }
        public string TENTIENGANH { get; set; }
        public string TENVIETTAT { get; set; }
        public string DIENTHOAI1 { get; set; }
        public string DIENTHOAI2 { get; set; }
        public string DIDONG { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYTHANHLAP { get; set; }
        public string TONGNHANVIEN { get; set; }
        public string SOCHINHANH { get; set; }
        public string SOTAIKHOAN { get; set; }
        public string MASOTHUE { get; set; }
        public Nullable<decimal> VONPHAPDINH { get; set; }
        public string GHICHUHOSOKHACHHANG { get; set; }
        public Nullable<bool> DULIEUNHOM { get; set; }
        public string NGUOIQUANLY { get; set; }
        public Nullable<int> ID_TINHTHANHPHO { get; set; }
        public Nullable<int> ID_QUANHUYEN { get; set; }
        public Nullable<int> ID_NHOMLINHVUC { get; set; }
        public Nullable<int> ID_LINHVUC { get; set; }
        public Nullable<int> ID_LOAIHINH { get; set; }
        public Nullable<int> ID_LOAIKHACHHANG { get; set; }
        public Nullable<int> ID_LOAIHOSOKH { get; set; }
        public Nullable<int> ID_PHANNHOM1 { get; set; }
        public Nullable<int> ID_PHANNHOM2 { get; set; }
        public Nullable<int> ID_NGANHANG { get; set; }
        public Nullable<int> ID_LOAIVPAR { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> J_KHACHHANGCHINHANH { get; set; }
        public Nullable<int> NHANHOAHONG { get; set; }
        public Nullable<bool> SINHNHAT { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public Nullable<int> J_KHACHHANGGIOITHIEU { get; set; }
        public Nullable<int> J_DTDTCGIOITHIEU { get; set; }
        public string QUYENDULIEU { get; set; }
        public Nullable<int> SOLUONGMAY { get; set; }
        public Nullable<int> ID_DATHANG { get; set; }
    }
}
