//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_HOPDONG
    {
        public int A_TH_HOPDONG { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public Nullable<int> J_TH_BAOGIA { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public int ID_DTTC { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public int J_DTDTC { get; set; }
        public Nullable<int> ID_LOAIHOPDONG { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<decimal> TYGIAVND { get; set; }
        public string SOHOPDONG { get; set; }
        public string TIEUDEHOPDONG { get; set; }
        public string NOIDUNGHOPDONG { get; set; }
        public Nullable<System.DateTime> NGAYKYHOPDONG { get; set; }
        public Nullable<System.DateTime> NGAYHIEULUCBAOHANH { get; set; }
        public Nullable<bool> KETTHUC { get; set; }
        public bool DULIEUNHOM { get; set; }
        public Nullable<decimal> TONGTIEN_CK { get; set; }
        public Nullable<decimal> TONGTIEN_HD { get; set; }
        public Nullable<decimal> TONGCONGTIEN { get; set; }
        public Nullable<bool> CHIETKHAUPT { get; set; }
        public Nullable<bool> NHIEUCOTGIA { get; set; }
        public Nullable<bool> XUATNHAP { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string QUYENDULIEU { get; set; }
        public string DANHSACHDUYET { get; set; }
        public Nullable<int> ID_MUCDICHHD { get; set; }
        public Nullable<bool> CHECKTYGIA { get; set; }
        public string DUPHONG1 { get; set; }
        public string DUPHONG2 { get; set; }
        public string SOTANGLUYKEHD { get; set; }
        public Nullable<decimal> CKTONGTIENHD { get; set; }
        public Nullable<bool> CHIETKHAUPTTONG { get; set; }
        public Nullable<decimal> TONGTIENHOPDONG_CK { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<int> J_SALE_LEADER { get; set; }
        public Nullable<int> J_GD_TRUNGTAM { get; set; }
        public Nullable<int> J_GD_VUNG { get; set; }
        public Nullable<int> SOBUOI { get; set; }
        public string TK_EC { get; set; }
        public string TK_CM { get; set; }
        public string TK_GDTT { get; set; }
        public string TK_GDV { get; set; }
        public string TK_EC_LEADER { get; set; }
        public string TK_CM_LEADER { get; set; }
    }
}
