//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_HOSODTDTC
    {
        public int A_HOSODTDTC { get; set; }
        public string MADTDTC { get; set; }
        public string TENDTDTC { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<int> GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAICOQUAN { get; set; }
        public string DIENTHOAINHARIENG { get; set; }
        public string DIDONG { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string SOTHICH { get; set; }
        public string GHICHUDTDTC { get; set; }
        public Nullable<bool> DUNGDAU { get; set; }
        public bool DULIEUNHOM { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public Nullable<int> ID_TINHTHANHPHO { get; set; }
        public Nullable<int> ID_QUANHUYEN { get; set; }
        public Nullable<int> ID_CHUCVU { get; set; }
        public Nullable<int> ID_LOAIDTDTC { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> ID_TRINHDO { get; set; }
        public Nullable<bool> SINHNHAT { get; set; }
        public string NICKSKYPE { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string MASOTHUE { get; set; }
        public Nullable<int> ID_GIOITINH { get; set; }
    }
}
