//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_HOPDONG_SPPT
    {
        public int A_TH_HOPDONG_SPPT { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_TH_BAOGIA_PT { get; set; }
        public Nullable<int> J_TH_DUBAO_PT { get; set; }
        public Nullable<int> J_TH_HOPDONG_PT { get; set; }
        public Nullable<int> J_SANPHAM { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> SOLUONGDANHAP { get; set; }
        public Nullable<decimal> DONGIA1 { get; set; }
        public Nullable<decimal> DONGIA2 { get; set; }
        public Nullable<decimal> DONGIA3 { get; set; }
        public Nullable<decimal> THANHTIEN1 { get; set; }
        public Nullable<decimal> THANHTIEN2 { get; set; }
        public Nullable<decimal> THANHTIEN3 { get; set; }
    }
}
