//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_HOSONHANVIEN
    {
        public int A_HOSONHANVIEN { get; set; }
        public string MANHANVIEN { get; set; }
        public string MACRM { get; set; }
        public string MAHRM { get; set; }
        public string TENNHANVIEN { get; set; }
        public Nullable<int> ID_LOAIKHACHHANG { get; set; }
        public Nullable<int> ID_BOPHAN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DOITAC_LIENHE { get; set; }
        public string DIACHI { get; set; }
        public string DIDONG { get; set; }
        public Nullable<int> ID_GIOITINH { get; set; }
        public Nullable<int> ID_CHUCVU { get; set; }
        public Nullable<int> ID_PHONGBAN { get; set; }
        public Nullable<int> ID_LOAINHANVIEN { get; set; }
        public Nullable<int> J_NGUOIQUANLY { get; set; }
        public Nullable<int> ID_PHANLOAINHANSU { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public string LOAIKHACHHANG { get; set; }
        public Nullable<int> MALMS { get; set; }
        public string TAIKHOAN { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> Sale_Leader { get; set; }
        public Nullable<int> CSO_Leader { get; set; }
        public string crm_vung { get; set; }
    }
}
