//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_HENLICH
    {
        public int A_TH_HENLICH { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> J_DTDTC { get; set; }
        public int J_KHACHHANG { get; set; }
        public Nullable<int> ID_LOAIHEN { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
        public Nullable<int> J_TH_BAOGIA { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<int> ID_TINHTHANHPHO { get; set; }
        public Nullable<int> ID_QUANHUYEN { get; set; }
        public Nullable<int> ID_PHUONGTHUC { get; set; }
        public Nullable<int> ID_CONGCU { get; set; }
        public Nullable<int> ID_REMAIDER { get; set; }
        public System.DateTime NGAYHEN { get; set; }
        public Nullable<int> GIOHEN { get; set; }
        public Nullable<int> PHUTHEN { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<bool> DULIEUNHOM { get; set; }
        public Nullable<bool> THUCHIEN { get; set; }
        public Nullable<System.DateTime> GIOHHEN { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string DANHSACHNGUOIHEN { get; set; }
        public Nullable<bool> ViewState { get; set; }
    }
}
