//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_KHAUHAO_S1
    {
        public int ID_TH_KHAUHAO_S1 { get; set; }
        public Nullable<int> A_SANPHAM { get; set; }
        public Nullable<decimal> GIATRICONLAI { get; set; }
        public Nullable<decimal> TIEUTHUCPHANBO { get; set; }
        public Nullable<decimal> TONGTIEUTHUC { get; set; }
        public Nullable<decimal> GIATRIKHAUHAOTRONGKY { get; set; }
        public Nullable<decimal> GIATRIDAKHAUHAOTRONGKY { get; set; }
        public Nullable<int> JD_DINHKHOAN_NO { get; set; }
        public Nullable<int> JD_DINHKHOAN_CO { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string MAY1 { get; set; }
        public string S1_ID { get; set; }
        public Nullable<System.DateTime> NGAYLAM { get; set; }
    }
}
