//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_KETCHUYEN_TK
    {
        public int A_KETCHUYEN_TK { get; set; }
        public Nullable<int> J_KETCHUYEN { get; set; }
        public string TUTAIKHOAN { get; set; }
        public string DENTAIKHOAN { get; set; }
        public Nullable<decimal> DUNO { get; set; }
        public Nullable<decimal> DUCO { get; set; }
        public string DINHKHOANNO { get; set; }
        public string DINHKHOANCO { get; set; }
    }
}
