//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_KEHOACH
    {
        public int A_KEHOACH { get; set; }
        public string TENKEHOACH { get; set; }
        public Nullable<System.DateTime> NGAYKEHOACHTU { get; set; }
        public Nullable<System.DateTime> NGAYKEHOACHDEN { get; set; }
        public Nullable<int> TONGKHACHHANGMUCTIEU { get; set; }
        public Nullable<int> TONGDOANHSOMUCTIEU { get; set; }
        public string NHIEMVUKHONGTHUONGXUYEN { get; set; }
        public string GHICHUKEHOACH { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public bool DULIEUNHOM { get; set; }
        public Nullable<decimal> TYGIA { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> ID_KENHBANHANG { get; set; }
        public Nullable<int> ID_NHIEMVUCHUAN { get; set; }
        public Nullable<int> ID_PHUONGTHUC { get; set; }
        public Nullable<int> ID_CONGCU { get; set; }
        public Nullable<bool> CHIETKHAUPT { get; set; }
        public string MAKS { get; set; }
        public Nullable<int> ID_LOAIKEHOACH { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIENKEHOACH { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUCKEHOACH { get; set; }
        public string MAKEHOACH { get; set; }
        public string NOIDUNGKEHOACH { get; set; }
        public byte[] IMG { get; set; }
        public string FILENAME { get; set; }
        public Nullable<int> ID_BOPHAN { get; set; }
        public Nullable<bool> ISDEL { get; set; }
        public Nullable<int> NGUOIDUNG2 { get; set; }
        public Nullable<System.DateTime> NGAY2 { get; set; }
        public Nullable<int> ID_TRUNGTAM { get; set; }
        public string MA_LMS { get; set; }
        public string MATRUNGTAM { get; set; }
        public Nullable<int> SOHOCSINH { get; set; }
    }
}
