//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_KETCHUYEN
    {
        public int A_KETCHUYEN { get; set; }
        public string MAKETCHUYEN { get; set; }
        public string TENKETCHUYEN { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<System.DateTime> NGAYKETCHUYEN { get; set; }
    }
}
