//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_KEHOACH_NTH
    {
        public int A_TH_KEHOACH_NTH { get; set; }
        public int J_KEHOACH { get; set; }
        public int ID_DTTC { get; set; }
        public string GHICHU { get; set; }
    }
}
