//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_KEHOACH_KHACHHANG
    {
        public int A_KEHOACH_KHACHHANG { get; set; }
        public int J_KEHOACH { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public Nullable<System.DateTime> NGAYHOANTHANH { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
    }
}
