//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_KEHOACH_SANPHAM
    {
        public int A_KEHOACH_SANPHAM { get; set; }
        public int J_KEHOACH { get; set; }
        public int J_SANPHAM { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<decimal> CHIETKHAU { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<decimal> THUEVAT { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public string NOTE4 { get; set; }
        public string NOTE5 { get; set; }
        public string NOTE6 { get; set; }
        public Nullable<decimal> SO_HOCSINHMAX { get; set; }
    }
}
