//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_MCC_DB_THO
    {
        public int A_MCC { get; set; }
        public int ID { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string IP { get; set; }
    }
}
