//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_NHAPHANG_SP_LOT
    {
        public int A_TH_NHANHANG_SP_LOT { get; set; }
        public int J_SANPHAM { get; set; }
        public string MALOT { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> SOLUONGTON { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<int> THUEVAT { get; set; }
        public Nullable<decimal> CHIETKHAU { get; set; }
        public Nullable<System.DateTime> NGAYHANSUDUNG { get; set; }
        public Nullable<System.DateTime> NGAYSANXUAT { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> DANGLAM { get; set; }
        public Nullable<decimal> NGUYENTE { get; set; }
        public Nullable<decimal> TTBANTE { get; set; }
        public Nullable<decimal> TTCHIETKHAU { get; set; }
        public Nullable<decimal> PTTHUEDB { get; set; }
        public Nullable<decimal> THUEDB { get; set; }
        public Nullable<decimal> PTTHUENK { get; set; }
        public Nullable<decimal> THUENK { get; set; }
        public Nullable<int> J_SANPHAM_DTCPSX { get; set; }
        public Nullable<int> J_SANPHAM_KMP { get; set; }
        public Nullable<int> J_SANPHAM_DTTHCP { get; set; }
        public Nullable<decimal> DONGIA1 { get; set; }
        public Nullable<decimal> DONGIA2 { get; set; }
        public Nullable<decimal> DONGIA3 { get; set; }
        public Nullable<decimal> THANHTIEN1 { get; set; }
        public Nullable<decimal> THANHTIEN2 { get; set; }
        public Nullable<decimal> THANHTIEN3 { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public Nullable<System.DateTime> DATENOTE { get; set; }
        public Nullable<decimal> DONGIA_LASTEST { get; set; }
        public Nullable<decimal> THANHTIEN_LASTEST { get; set; }
        public string BTGT_LASTEST { get; set; }
        public Nullable<int> REF_A_THUCHIEN_TGT { get; set; }
        public Nullable<int> JD_DINHKHOAN_NO { get; set; }
        public Nullable<int> JD_DINHKHOAN_CO { get; set; }
    }
}
