//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_NHANTHU
    {
        public int A_TH_NHANTHU { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> ID_MUCDICH { get; set; }
        public Nullable<int> ID_LOAITHU { get; set; }
        public string MANHANTHU { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYIN { get; set; }
        public bool DULIEUNHOM { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
    }
}
