//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_NHAPHANG
    {
        public int A_TH_NHAPHANG { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
        public int J_DTDTC { get; set; }
        public int ID_KHOHANG { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> ID_BOPHAN { get; set; }
        public Nullable<int> ID_PHANXUONG { get; set; }
        public Nullable<int> ID_PHANLOAIXN1 { get; set; }
        public Nullable<int> ID_PHANLOAIXN2 { get; set; }
        public Nullable<int> ID_HANGVANCHUYEN { get; set; }
        public Nullable<int> ID_DINHKHOAN_NO { get; set; }
        public Nullable<int> ID_DINHKHOAN_CO { get; set; }
        public Nullable<int> ID_TOKHAINHAPKHAU { get; set; }
        public Nullable<int> ID_LOAIPHIEUNHAP { get; set; }
        public string MANHAPHANG { get; set; }
        public string SOPHIEUNHAP { get; set; }
        public string DIACHINHAPHANG { get; set; }
        public string SOVANDON { get; set; }
        public string GHICHUNHAPHANG { get; set; }
        public string DUPHONG1 { get; set; }
        public string DUPHONG2 { get; set; }
        public string DUPHONG3 { get; set; }
        public string DUPHONG4 { get; set; }
        public Nullable<decimal> TONGTIENCHENH { get; set; }
        public Nullable<decimal> TONGTIENNHAPHANG { get; set; }
        public Nullable<decimal> TONGTIENTHUE { get; set; }
        public Nullable<decimal> TYGIA { get; set; }
        public Nullable<bool> CHECKTUYETDOI_THUE { get; set; }
        public Nullable<bool> DULIEUNHOM { get; set; }
        public Nullable<System.DateTime> NGAYNHAPHANG { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string QUYENDULIEU { get; set; }
        public Nullable<System.DateTime> NGAYHOADON { get; set; }
        public string SOHOADON { get; set; }
        public string SERIHHOADON { get; set; }
        public string MAUSOHD { get; set; }
        public Nullable<int> RefNH { get; set; }
        public Nullable<bool> CHIETKHAUPT { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<decimal> CKTONGTIENNH { get; set; }
        public Nullable<bool> CHIETKHAUPTTONG { get; set; }
        public Nullable<decimal> TONGTIENNHAPHANG_CK { get; set; }
        public Nullable<bool> DK_NO { get; set; }
        public Nullable<bool> DK_CO { get; set; }
    }
}
