//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_SANPHAM_TSCD
    {
        public int A_SANPHAM_TSCD { get; set; }
        public Nullable<int> J_SANPHAM { get; set; }
        public Nullable<decimal> NGUYENGIA { get; set; }
        public Nullable<int> THOIGIANKHAUHAO { get; set; }
        public Nullable<decimal> DONGIAKHAUHAO { get; set; }
        public Nullable<int> ID_DINHKHOAN_NO { get; set; }
        public Nullable<int> ID_DINHKHOAN_CO { get; set; }
        public Nullable<decimal> GIATRICONLAI { get; set; }
        public Nullable<int> THOIGIANCONLAI { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> NGAYMUAHANG { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
    }
}
