//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_SMS
    {
        public int A_TH_SMS { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public Nullable<int> ID_MUCDICH { get; set; }
        public Nullable<int> ID_DTTC { get; set; }
        public Nullable<int> ID_LOAISMS { get; set; }
        public string NGUOIGUI { get; set; }
        public string NGUOINHAN { get; set; }
        public string DONGGUICC { get; set; }
        public string TIEUDE_SMS { get; set; }
        public Nullable<System.DateTime> NGAYGUI_SMS { get; set; }
        public string NOIDUNG_SMS { get; set; }
        public Nullable<int> SOLANGUI { get; set; }
        public Nullable<bool> UCS2 { get; set; }
        public Nullable<bool> ALERT { get; set; }
        public string DIENTHOAI { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
        public bool DULIEUNHOM { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string MAKS { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIEN { get; set; }
        public Nullable<bool> SMSHENGIO { get; set; }
        public Nullable<int> GIOGUI { get; set; }
        public Nullable<bool> SKYPE { get; set; }
    }
}
