//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_SANPHAM_SR
    {
        public int A_TH_SANPHAM_SR { get; set; }
        public int J_SANPHAM { get; set; }
        public string SERINUMBER { get; set; }
        public bool DAXUAT { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<int> J_TH_XUATHANG { get; set; }
    }
}
