//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_SANPHAM
    {
        public int A_SANPHAM { get; set; }
        public string MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public string MODEL { get; set; }
        public string NHAPHANPHOI { get; set; }
        public Nullable<System.DateTime> NGAYSANXUAT { get; set; }
        public Nullable<int> SOTHANGBAOHANH { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<decimal> CHIETKHAU { get; set; }
        public string DACTINHKYTHUAT { get; set; }
        public string GHICHUSANPHAM { get; set; }
        public Nullable<bool> SANPHAM_CT { get; set; }
        public byte[] IMAGE { get; set; }
        public Nullable<bool> DULIEUNHOM { get; set; }
        public Nullable<int> ID_LOAISANPHAM { get; set; }
        public Nullable<int> ID_NHOMSANPHAM { get; set; }
        public Nullable<int> ID_NUOCSANXUAT { get; set; }
        public Nullable<int> ID_HANGSANXUAT { get; set; }
        public Nullable<int> ID_DONVITINH { get; set; }
        public Nullable<int> ID_PHANLOAI1 { get; set; }
        public Nullable<int> ID_PHANLOAI2 { get; set; }
        public Nullable<int> ID_PHANLOAI3 { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string QUYENDULIEU { get; set; }
        public Nullable<int> ID_MUCSANPHAM { get; set; }
        public Nullable<System.DateTime> NGAYDUPHONG1 { get; set; }
        public Nullable<System.DateTime> NGAYDUPHONG2 { get; set; }
        public Nullable<System.DateTime> NGAYDUPHONG3 { get; set; }
        public string GHICHUSANPHAM1 { get; set; }
        public Nullable<int> ID_DINHKHOAN_KHO { get; set; }
        public Nullable<int> ID_DINHKHOAN_NO { get; set; }
        public Nullable<int> ID_DINHKHOAN_CO { get; set; }
        public Nullable<int> A_THUCHIEN { get; set; }
        public Nullable<int> ID_LYDO_HV { get; set; }
        public string TINHTRANGSUDUNG { get; set; }
        public Nullable<int> ID_CHINHANH { get; set; }
        public Nullable<int> ID_PHONGBAN { get; set; }
        public Nullable<int> MA_LMS { get; set; }
        public Nullable<int> ID_PRODUCT_LMS { get; set; }
    }
}
