//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_SANPHAM_DONVI
    {
        public int A_SANPHAM { get; set; }
        public int ID_DONVITINH { get; set; }
        public decimal SOLUONG01 { get; set; }
        public int ID_DONVITINH02 { get; set; }
        public decimal SOLUONG02 { get; set; }
        public System.DateTime NGAY1 { get; set; }
    }
}
