//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_SMS_NHAN
    {
        public int A_SMS_NHAN_TINNHAN { get; set; }
        public string NGUOIGUI { get; set; }
        public Nullable<System.DateTime> NGAYGUI { get; set; }
        public string NOIDUNG { get; set; }
    }
}
