//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_SANPHAM_CT
    {
        public int A_TH_SANPHAM_CT { get; set; }
        public int J_SANPHAM { get; set; }
        public decimal SOLUONG { get; set; }
        public int J_SANPHAM_ME { get; set; }
        public string DUPHONG1 { get; set; }
        public string DUPHONG2 { get; set; }
        public string GHICHU { get; set; }
    }
}
