//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_THIETLAPCA
    {
        public int A_TH_THIETLAPCA { get; set; }
        public Nullable<int> ID_CHINHANH { get; set; }
        public Nullable<System.TimeSpan> GIOVAO { get; set; }
        public Nullable<System.TimeSpan> GIORA { get; set; }
        public string GHICHU { get; set; }
    }
}
