//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_THONGKE
    {
        public int A_TH_THONGKE { get; set; }
        public string MAMAY { get; set; }
        public string TENMAY { get; set; }
        public string MAKH { get; set; }
        public string TENKHACHHANG { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string DIENTHOAI { get; set; }
        public string FAX { get; set; }
        public Nullable<decimal> SOLANDUNG { get; set; }
        public Nullable<decimal> GIAODICH { get; set; }
        public Nullable<decimal> NHANTHU { get; set; }
        public Nullable<decimal> COUNTEMAIL { get; set; }
        public Nullable<decimal> SMS { get; set; }
        public Nullable<decimal> BAOGIA { get; set; }
        public Nullable<decimal> DUBAO { get; set; }
        public Nullable<decimal> HOPDONG { get; set; }
        public Nullable<decimal> XUATHANG { get; set; }
        public Nullable<decimal> THUTIEN { get; set; }
        public Nullable<decimal> NHAPHANG { get; set; }
        public Nullable<decimal> CHITIEN { get; set; }
        public Nullable<int> SOLUONGMAY { get; set; }
        public Nullable<System.DateTime> NGAYTHONGKE { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
        public Nullable<decimal> SUDUNGMAU { get; set; }
        public Nullable<System.DateTime> NGAYCAPDANGKY { get; set; }
    }
}
