//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_WORKINGTIMEDAILY
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Office { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string Ngayin { get; set; }
        public string Officail { get; set; }
        public string Seniorityyear { get; set; }
        public string Senioritymouth { get; set; }
        public string Senioritydate { get; set; }
        public string Annual_Leave_Remainings { get; set; }
        public string Annual_Leave_by_TODAY_based_on_seniority { get; set; }
        public string Annual_Leave_by_Dec_based_on_seniority { get; set; }
        public string Total_Anunual_Leave { get; set; }
        public string Day_off_mouth { get; set; }
        public string Annual_Leave_Remainings_in { get; set; }
        public string J_HOSO_KHACHHANG { get; set; }
        public Nullable<System.DateTime> NGAYTINH { get; set; }
    }
}
