//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_XUATHANG_HIS
    {
        public int A_TH_XUATHANG { get; set; }
        public int J_HOSOKHACHHANG { get; set; }
        public Nullable<int> J_TH_DUBAO { get; set; }
        public Nullable<int> J_TH_HOPDONG { get; set; }
        public Nullable<int> J_DTDTC { get; set; }
        public int ID_DTTC { get; set; }
        public Nullable<int> ID_BOPHAN { get; set; }
        public Nullable<int> ID_PHANXUONG { get; set; }
        public Nullable<int> ID_DINHKHOAN_NO { get; set; }
        public Nullable<int> ID_DINHKHOAN_CO { get; set; }
        public Nullable<int> ID_KHOHANG { get; set; }
        public Nullable<int> ID_KHOHANGCHUYEN { get; set; }
        public Nullable<int> J_TH_NHAPHANG { get; set; }
        public Nullable<int> ID_PHANLOAIXN1 { get; set; }
        public Nullable<int> ID_PHANLOAIXN2 { get; set; }
        public Nullable<int> ID_HANGVANCHUYEN { get; set; }
        public Nullable<int> ID_LOAIPHIEUXUAT { get; set; }
        public string MAXUATHANG { get; set; }
        public string SOPHIEUXUAT { get; set; }
        public string DIACHIXUATHANG { get; set; }
        public string SOVANDON { get; set; }
        public string GHICHUXUATHANG { get; set; }
        public string DUPHONG1 { get; set; }
        public string DUPHONG2 { get; set; }
        public bool DULIEUNHOM { get; set; }
        public Nullable<System.DateTime> NGAYXUATHANG { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public Nullable<decimal> TONGTIENCK { get; set; }
        public Nullable<decimal> TONGTIENXH { get; set; }
        public Nullable<decimal> TONGTIENTHUE { get; set; }
        public Nullable<decimal> TYGIA { get; set; }
        public Nullable<bool> CHECKTUYETDOI_THUE { get; set; }
        public Nullable<int> NGUOIDUNG1 { get; set; }
        public string MAY1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string QUYENDULIEU { get; set; }
        public Nullable<System.DateTime> NGAYHOADON { get; set; }
        public string SOHOADON { get; set; }
        public string SERIHHOADON { get; set; }
        public string MAUSOHD { get; set; }
        public Nullable<int> RefXH { get; set; }
        public Nullable<bool> CHIETKHAUPT { get; set; }
        public Nullable<int> ID_LOAITIEN { get; set; }
        public Nullable<decimal> CKTONGTIENXH { get; set; }
        public Nullable<bool> CHIETKHAUPTTONG { get; set; }
        public Nullable<decimal> TONGTIENXUATHANG_CK { get; set; }
        public Nullable<System.DateTime> NGAY1_LAST { get; set; }
        public string MAY1_LAST { get; set; }
        public string NGUOIDUNG1_LAST { get; set; }
    }
}
