//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Apax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_henlich
    {
        public string BUTTON { get; set; }
        public Nullable<bool> CHON { get; set; }
        public string MAKH { get; set; }
        public string TENKHACHHANG { get; set; }
        public string TENLOAIHEN { get; set; }
        public string NOIDUNG { get; set; }
        public System.DateTime NGAYHEN { get; set; }
        public string GIOHEN { get; set; }
        public Nullable<bool> THUCHIEN { get; set; }
        public Nullable<int> A_HOSOKHACHHANG { get; set; }
        public int A_TH_HENLICH { get; set; }
        public Nullable<int> J_KEHOACH { get; set; }
        public string TENDTTC { get; set; }
        public string TENDTDTC { get; set; }
        public string NGUOILAMTHUCHIEN { get; set; }
        public string TENLYDOHV { get; set; }
        public string TENLYDOTD { get; set; }
        public string TENLYDONT { get; set; }
        public string GHICHU { get; set; }
        public string HD_MUCDICH { get; set; }
        public string LOAITHUCHIEN { get; set; }
    }
}
